// GVMC Main Contacts Data
const GVMC_CONTACTS = [
  { sno:1,  office:"GVMC", name:"Sri Ketan Garg, I.A.S", designation:"Commissioner", contact:"Grievance: 180042500009\n2568545 (Fax)\nWhatsApp: 9666909192", email:"Commissioner_gvmc@yahoo.co.in" },
  { sno:2,  office:"GVMC", name:"Sri S S Varma", designation:"Additional Commissioner (F)", contact:"8374889555", email:"" },
  { sno:3,  office:"GVMC", name:"Sri D V Ramana Murthy", designation:"Additional Commissioner (R) Revenue", contact:"9182147677", email:"" },
  { sno:4,  office:"GVMC", name:"Sri P Nallanayya", designation:"Additional Commissioner (PH)", contact:"7997157979", email:"" },
  { sno:5,  office:"GVMC", name:"Smt P M Satyaveni", designation:"Additional Commissioner General", contact:"9948254463", email:"" },
  { sno:6,  office:"GVMC", name:"Smt D VijayaBharathi", designation:"Joint Director", contact:"8008128229", email:"" },
  { sno:7,  office:"GVMC", name:"Sri S Srinivasa Rao", designation:"DCR – Revenue", contact:"9912349437", email:"" },
  { sno:8,  office:"GVMC", name:"Dr E N V Naresh Kumar", designation:"CMOH", contact:"9848308823", email:"" },
  { sno:9,  office:"GVMC", name:"Sri A Prabhakar Rao", designation:"CCP", contact:"8187892355", email:"" },
  { sno:10, office:"GVMC", name:"Sri P. V. V Satyanarayana Raju", designation:"Chief Engineer", contact:"7337401813", email:"" },
  { sno:11, office:"GVMC", name:"Smt N Sarojini", designation:"Project Director (UCD)", contact:"7901610051", email:"" },
  { sno:12, office:"GVMC", name:"Sri B V Ramana", designation:"Secretary", contact:"9666777182", email:"" },
  { sno:13, office:"GVMC", name:"Sri C C Vasudeva Reddy", designation:"Examiner of Accounts", contact:"7993453488", email:"" },
  { sno:14, office:"GVMC", name:"Smt. Aruna Kumari", designation:"Asst. Examiner of Accounts", contact:"8500974866", email:"" },
  { sno:15, office:"GVMC", name:"Dr D Sambha Murthy", designation:"Biologist I", contact:"9100372699", email:"" },
  { sno:16, office:"GVMC", name:"Dr G Vara Prasad Reddy", designation:"Biologist II", contact:"9985753543", email:"" },
  { sno:17, office:"GVMC", name:"Dr Raja Ravi", designation:"CVO", contact:"8639904373", email:"" },
  { sno:18, office:"GVMC", name:"Sri P D V Prasadarao", designation:"Statistical Officer", contact:"9948078507", email:"" },
  { sno:19, office:"GVMC", name:"—", designation:"Dy. Director Horticulture (i/c)", contact:"—", email:"" },
  { sno:20, office:"GVMC", name:"Sri E Appala Raju", designation:"Director of Sports", contact:"9160851448", email:"" },
  { sno:21, office:"GVMC", name:"Sri T Nagendra Kumar", designation:"Zonal Commissioner – Bheemili", contact:"9849905798", email:"" },
  { sno:22, office:"GVMC", name:"Sri V Ippili Naidu", designation:"Zonal Commissioner – Madhurawada", contact:"9849905798", email:"" },
  { sno:23, office:"GVMC", name:"Sri K Siva Prasad", designation:"Zonal Commissioner – East Asilmetta", contact:"9912349486", email:"" },
  { sno:24, office:"GVMC", name:"Sri M Mallayya Naidu", designation:"Zonal Commissioner – South (Suryabagh)", contact:"9848889701", email:"" },
  { sno:25, office:"GVMC", name:"Sri B Ramu", designation:"Zonal Commissioner – North (Madhavadhara)", contact:"9705086888", email:"" },
  { sno:26, office:"GVMC", name:"Smt K Hemavathi", designation:"Zonal Commissioner – West (Gnanapuram)", contact:"9912349439", email:"" },
  { sno:27, office:"GVMC", name:"Sri B R S Seshadri", designation:"Zonal Commissioner – Gajuwaka", contact:"9666673949", email:"" },
  { sno:28, office:"GVMC", name:"Sri Chakravarthi", designation:"Zonal Commissioner – Anakapalli", contact:"8340999957", email:"" },
  { sno:29, office:"GVMC", name:"Smt Manisha Tripathi", designation:"Zonal Commissioner – Aganampudi", contact:"9912872224", email:"" },
  { sno:30, office:"GVMC", name:"Sri H Shankar Rao", designation:"Zonal Commissioner – Pendhurthi", contact:"9912349434", email:"" },
  { sno:31, office:"GVMC", name:"A PrabhakaraRao", designation:"CCP", contact:"8187892355", email:"" },
  { sno:32, office:"GVMC", name:"Sri K Dhanunjay Reddy", designation:"Circle Commissioner 1–4", contact:"9390404003", email:"" },
  { sno:33, office:"GVMC", name:"Sri K Dhanunjay Reddy", designation:"Circle Commissioner 5–8", contact:"9390404003", email:"" },
  { sno:34, office:"GVMC", name:"Sri K Venkateswara Rao", designation:"DCP – 1", contact:"7729995933", email:"" },
  { sno:35, office:"GVMC", name:"Sri K Haridas", designation:"DCP – 2", contact:"9573535335", email:"" },
  { sno:36, office:"GVMC", name:"Sri Ch Madhusudhana Rao", designation:"DCP – 3", contact:"7997549222", email:"" },
  { sno:37, office:"GVMC", name:"Sri T G Ram Mohan", designation:"DCP – 4", contact:"8187898435", email:"" },
  { sno:38, office:"GVMC", name:"Sri K Shanthi Raju", designation:"Superintending Engineer – 1", contact:"9948095518", email:"" },
  { sno:39, office:"GVMC", name:"Sri K Shanthi Raju", designation:"Superintending Engineer – 2", contact:"9948095518", email:"" },
  { sno:40, office:"GVMC", name:"Sri T Sampath", designation:"Superintending Engineer – 3", contact:"8187899217", email:"" },
  { sno:41, office:"GVMC", name:"Sri G Govindha Rao", designation:"Superintending Engineer – 4", contact:"7997549666", email:"" },
  { sno:42, office:"GVMC", name:"Sri K Srinivasa Rao", designation:"Superintending Engineer – 5", contact:"9951532876", email:"" },
  { sno:43, office:"GVMC", name:"Sri G Govindha Rao", designation:"Superintending Engineer – 6", contact:"9010605131", email:"" },
  { sno:44, office:"GVMC", name:"Sri G V Pallam Raju", designation:"Superintending Engineer – 7", contact:"8187896437", email:"" },
  { sno:45, office:"GVMC", name:"Sri Ch Yedukondalu", designation:"Superintending Engineer – 8", contact:"9848308824", email:"" },
  { sno:46, office:"GVMC", name:"Sri G V Pallam Raju", designation:"Superintending Engineer – Water Supply, UGD & Projects", contact:"8187896437", email:"" },
];
