// Auto-generated from GVMC Corporators Ward Wise Area Details PDF
// Total wards: 97
// Total unique areas: 1332

const WARD_AREAS = {
  "1": [
    "Bunglow Metta",
    "Vempadavariveedhi",
    "Kapuveedhi",
    "Kondapeta",
    "Kondapeta Colony",
    "Alankavariveedhi",
    "Wilsonpeta",
    "Wilson Peta Company Quarters",
    "Jutemill Quarters & ZP High school",
    "Kothapeta Vani School Area",
    "Reddika Veedhi",
    "Bogguroad",
    "Perikiveedhi- Chiilla peta",
    "Parimi Thammayya Lane",
    "Thippana vari Veedhi",
    "Kuncham Apprao Street",
    "Chinthalapudi Apparao street",
    "Jogavari veedhi",
    "Local Office road",
    "Thata Theatre Area",
    "Kusumuri vari veedhi and Yellamma gudi Area",
    "Ramannapeta",
    "Nagarapuveedhi",
    "Balaji"
  ],
  "2": [
    "Sabbivanipeta",
    "ESI Hospital Quarters",
    "Grandhalayam veedhi",
    "VUDA complex",
    "Konda Area",
    "Satyanarayana peta Market Road",
    "Hospital",
    "Ramalayam Temple Area.NTR Kalyna Mandapam",
    "Venkateswara Theatre to Bora Guruvula reddy Street",
    "Kummari Jeerupeta",
    "Chillapeta",
    "Keetin peta Church area",
    "Mini Stadium",
    "Pallikummaripalem",
    "Rayipalem",
    "Rajalingampeta",
    "Yathakummaripalem",
    "Gorinta Poultries area",
    "Amg area",
    "Muslims thota",
    "Relliveedhi",
    "Mamidipalem",
    "Dekkatipalem",
    "Guruvu gari thota Area",
    "Nammivanipeta colony",
    "Nammivanipeta",
    "Koradapeta",
    "Jeerupeta",
    "Karri nammi vanipeta",
    "pasi barli vari Kallalu",
    "Edadhasaripeta",
    "Chakali peta",
    "Akkaramani Ramunaidu House area",
    "Sangivalasa Colony",
    "Sangivalasa",
    "Valadhapeta part"
  ],
  "3": [
    "Telephone Exchange Area",
    "Medharavedhi",
    "thotaveedhi",
    "2nd ward Front of the MUP school",
    "Cinema hall Area",
    "Dutch Road",
    "Old iti",
    "Kummaripalem road",
    "Gaduveedhi",
    "MDO office Quarters veedhi",
    "Krishnayya Veedhi",
    "Saraswathi Samajam",
    "Gantasthambham Area.Scavangers Colony Relliveedhi",
    "Burma Colony",
    "Smith street",
    "Nalli Veedhi",
    "Sai baba Temple",
    "Subhash Road",
    "Gedda veedhi",
    "Maseedh Area",
    "Thotaveedhi",
    "St. Anns Grounds",
    "Bank Road",
    "Appikonda veedhi",
    "Vaddipolamma gudi area",
    "Kallaveedhi",
    "Nehru school Area",
    "Chilakavariveedhi",
    "Lankadavari veedhi",
    "Old Bus Stand Area",
    "CBM School",
    "Bukkidora meda",
    "Nehru street",
    "AB Chruch Area Area",
    "Reddikaveedhi",
    "Municipal High School Area",
    "Golla veedhi",
    "Kanyakaparameswara gudi veedhi",
    "Motilal Veedhi",
    "Yatha veedhi",
    "Pandaveedhi",
    "Sivalyam Temple Area",
    "Nookalamma Gudi Veedhi",
    "Narasimha Swamy Temple Road",
    "Bramhana veedhi",
    "Boyiveedhi",
    "Court area",
    "Narasimha swamy temple Area",
    "Golla street",
    "Ntr Colony",
    "Sub - registrer Office Area",
    "Diet Area",
    "Govt. Hospital area",
    "Mangala veedhi",
    "Yeguvapeta",
    "Srihari gari House area",
    "Police Quarters area",
    "Kothapeta Tank Area",
    "ZP Guest Housearea",
    "Nerella valasa Colony",
    "Residential School area",
    "Beach Road",
    "Nerellavalasa Hill area (OG)",
    "Gadu Veedhi",
    "Kondapeta",
    "Konkiveedhi",
    "Ganagalla vari veedhi",
    "Durga Ashramma area",
    "Hostel area",
    "Krishna colony",
    "Gollapalem"
  ],
  "4": [],
  "5": [
    "Boyyipalem Junction",
    "Paradesi palem",
    "EWS Colony",
    "JK Layout",
    "Ambedkar colony",
    "Boravanipalem",
    "Marikavalasa NGO's Drivers Colony",
    "Kommadi Village",
    "Kommadi",
    "Kommadi SC Colony",
    "Sai Ram Colony",
    "Amrutha Arcade",
    "Nagarampalem Village",
    "Carpenter Colony",
    "Swayamkrushi nagar",
    "Ayyappa nagar",
    "Vivekananda colony",
    "Vikalangula Colony",
    "Ganeshnagar Road",
    "Dockyard Colony",
    "Bottavanipalem",
    "Sadguru Sai Colony",
    "Sri laxmi nagar",
    "Siva shakti nagar",
    "Paradesipalem",
    "Marikavalasa Hill",
    "Rajeev Gruha Kalpa type-I",
    "Nr. Techno School",
    "Rajeev Gruha Kalpa type-II",
    "Rajeev Gruha Kalpa",
    "Near Marikavalasa"
  ],
  "6": [
    "Car shed Junction",
    "Laxmivanipalem",
    "RH Colony",
    "Usmania Colony",
    "HB Colony",
    "Ashok Nagar",
    "Ratana Residency",
    "Anand Residency",
    "Bakkannapalem",
    "NTR Colony",
    "FCI Layout",
    "Gayatri Nagar",
    "Sai Priya Garden",
    "Chandrampalem",
    "Madhurawada Junction",
    "Bhagavandas Colony",
    "Kommadi Junction & Vasantha vihar",
    "Siddardha nagar",
    "GCC Layout",
    "Srinivasa nagar",
    "Devimetta",
    "Nagarampalem Village"
  ],
  "7": [
    "Vambay Colony (Blocks) 1A",
    "Krishna Nagar",
    "Madhurawada Junction",
    "Port Colony",
    "Sub-Registrar Area",
    "Kalanagar",
    "Mallayyapalem",
    "Mallayyapalem SC Colony",
    "SKML Layout",
    "Vambay Colony A",
    "Z Vambay Colony 20AA to 24A Vambay Colony 24B to 26B",
    "27A to 29B",
    "34A to 36A",
    "36B to 40B",
    "41A to 44A",
    "44B to 47 B",
    "Ganeshnagar Road",
    "Priyadarsini Colony",
    "Dhobi Colony",
    "Tailors Colony",
    "Madhurawada Jn",
    "Bapujinagar",
    "Swatantra nagar",
    "Bottavanipalem",
    "Dobhi Colony",
    "Shyam nagar",
    "Srinivas nagar",
    "Ayodhya nagar",
    "Timmapuram",
    "AP HB Colony",
    "Mithilapuri Vuda Colony",
    "Old Madhurawada",
    "RTC Colony",
    "Manam Anjaneyulu Colony"
  ],
  "8": [
    "Law College",
    "HB Colony",
    "Chanukyapuri Layout",
    "Sundarnagar",
    "Tarakaramanagar",
    "P.K.Palem",
    "Old PM Palem",
    "Mithilapuri Vuda Colony",
    "Ramaraju Enclave",
    "Vikalangual colony",
    "AP Revenue Layout",
    "Musalayyapalem",
    "Gudlavanipalem",
    "Sagarnagar HIG-1",
    "Sagarnagar HIG-II HIG-IA & MIG-A",
    "Sagarnagar MIG-A",
    "Sagarnagar MIG-B",
    "Sagarnagar MIG-D",
    "Sagarnagar LIG-A",
    "Sagarnagar LIG- B",
    "Sagarnagar LIG-C",
    "Thatichetlapalem",
    "Bhuvaneswari colony",
    "Subhash Sirigudi nagar",
    "Gollala yendada",
    "Mubarak colony",
    "Chinna Rushikonda",
    "Chinna Rushikonda Ommivanipalem",
    "Peda Rushikonda Swarna Bharathi nagar",
    "Swarna Bharathi nagar",
    "SB nagar",
    "Durga Nagar",
    "Chandram palem Village NGO'S Layout",
    "Chandrampalem",
    "Old Madhurawada"
  ],
  "9": [
    "JODUGULLAPALEM",
    "VISALAKSHINAGAR",
    "Ramalayam Street",
    "Sanjay nagar",
    "Sanjeev nagar colony",
    "SC &ST colony",
    "Visalakshi Nagar",
    "Chalapti Nagar",
    "Jodugullapalem",
    "Dayal nagar",
    "Police Quarters",
    "Dairy farm"
  ],
  "10": [
    "Thotagaruvu"
  ],
  "11": [
    "Raveendra Nagar -II",
    "Srihari Nagar",
    "Gandhi Nagar",
    "Vivekananda nagar",
    "Priyadarshini nagar",
    "Priyadarshini colony",
    "Balaji nagar",
    "Anna nagar. Thotagaruvu",
    "Sri ram nagar",
    "Krishna nagar",
    "Gandhi nagar",
    "Arilova Sector-I",
    "Kranthi nagar - I &II",
    "Kranthi nagar ST Colony",
    "Mayuri nagar",
    "Durga nagar",
    "BTR nagar & BC colony",
    "Apsara colony & Bharat nagar",
    "Bharath nagar & Mustapha colony",
    "Mustapha colony",
    "Madhu Hill view Residency",
    "Aprasa colony -II & Drivers colony",
    "Swamy Vivekananda nagar & Rajiv nagar",
    "TSI point",
    "SRINIVASA Residency & Devi Towers",
    "Ravindra Nagar",
    "SIG Nagar"
  ],
  "12": [
    "Rajiv nagar & Central prison",
    "Surya teja nagar",
    "Parvathi nagar",
    "BTR nagar",
    "Nehru nagar",
    "Leela sundar nagar",
    "Ambedkar New colony",
    "Durga nagar & Ambedkar nagar",
    "Durga nagar & Sundarayya nagar",
    "Durga nagar & Parvathi"
  ],
  "13": [
    "Sundarayya nagar",
    "Nehru nagar",
    "Verni Durga nagar",
    "Vishnupuri colony",
    "Siva sankar nagar",
    "Bhagatsingh nagar",
    "Sivaji nagar - I",
    "NMR colony",
    "Durga bazar",
    "Sai nagar",
    "ASR nagar",
    "Laxmi nagar",
    "Pandurangapuram",
    "Operation colony",
    "SKML nagar",
    "Jai Bheem nagar",
    "Laxmi parvathi nagar",
    "Sivaji nagar",
    "Srikrishna puram",
    "Pineapple colony",
    "Central prison area"
  ],
  "14": [
    "MK’S KODANDARAMAYYA ENCLAVE",
    "MADHURA Backside",
    "Divya Sakthi Apartment Line",
    "Vidyuthnagar",
    "Near Port Ground Westside",
    "Near Velama Bhavanam",
    "Near Swarna Residents",
    "Near Sampath Villas Aprt",
    "B S Layout",
    "Raghavendra Nursing home area",
    "Andhra Bank ATM opposite",
    "Presidential School area",
    "Near More Super Market",
    "Kshatriya Kalyana Mandapam",
    "bilal Colony",
    "ASR Nagar"
  ],
  "15": [
    "Seethammadhara Junction",
    "APSEB Colony",
    "Doctors Colony",
    "Ambedkar Nagar",
    "VUDA Apts",
    "LIC Qtrs",
    "MMTC Colony",
    "H.B.Colony Steel Plant Qtrs",
    "(part)",
    "Simhadripuram Up Area",
    "Durganagar",
    "J R Nagar",
    "Sivasenkari Nagar",
    "Old Venkojipalem",
    "Uma Nagar",
    "Adarshnagar",
    "Lakshmi Narasimha Nagar"
  ],
  "16": [
    "HB Colony",
    "Steel Plant Quarters(part)",
    "KRM Colony part",
    "Shivalalyam Opposite",
    "Chakalipeta",
    "Maddilapalem Backside",
    "Bhanunagar",
    "Krishna College back side",
    "GO Colony",
    "Isukathota Village",
    "Maddilapalem Bazar road",
    "SC Colony"
  ],
  "17": [
    "Kotha Venkojipalem",
    "Housing Board Office Area",
    "Teja Apartment Backside",
    "Near Sanjeeva Hospital",
    "Sector-1 MVP Colony",
    "Near Veera Brhammam Temple",
    "Sector 4 MVP Colony",
    "Near Isukathota Petrol Bunk Backside",
    "Girijana Bhavan Area Sector- 5 MVP Colony",
    "SDAH High School Area Sector-5 MVP Colony",
    "Near AQJ Central Office",
    "State Bank Colony and Sector-8 MVP Colony",
    "Opp: Sarvani Sweets",
    "Satyasai School Area",
    "TTD Kalyanamandapam Opposite area",
    "Lakshmi Nagar",
    "AADARSHA Nagar",
    "Ramalakshmi Aprt",
    "Indira Nagar",
    "Pedawaltair",
    "Beside Ranga Residency",
    "Yeeta Peta",
    "Pedawaltair Village",
    "Ratna Nivas",
    "Dallivani Veedi",
    "Fish Market Road",
    "Sulab Complex",
    "Vizayanagar Colony",
    "Padmanabha Apartment"
  ],
  "18": [
    "Samatha college area",
    "MVP Sector- 9 & 10",
    "Golla Veedhi",
    "Kailashagiri Konda route lane",
    "Relli Veedhi",
    "Fishermen colony",
    "Muvvalavanipalem",
    "Vasavanipalem",
    "A S Raja ground area",
    "MVP Sector 2",
    "& 7 area",
    "Cancer Hospital area",
    "Sivaganesh nagar"
  ],
  "19": [
    "MVP Sector-12",
    "Opp: A S Raja Ground",
    "MVP Sector-11",
    "Gedda beside line",
    "Ushodaya Main Road to Gedda line",
    "Ushodaya main road to Nandhi Temple backside",
    "Opp KKR Gowtham School Lawsonsbay Colony",
    "Sri Krishna Chaitanya Gurukula Asramam",
    "Opp: Post Office",
    "Opp:Santhi Asramam",
    "Beach Road",
    "Opp: MD Yathra Nivas",
    "Vasuvanipalem",
    "Jalaripeta"
  ],
  "20": [
    "GOLLALAPALEM",
    "BHEMUNIPATNMA-531163 Peawaltari Junction",
    "Swati Petrol Bunk area",
    "Visakha Eye Hospital area",
    "Vijayanagar Palace layout area",
    "Shramika Nagar",
    "Nethaji Veedhi Chinawaltair",
    "Rajaka Veedhi",
    "Kanakammavari Gudi area",
    "East Point colony",
    "Kagitalavari Veedhi",
    "Palikalavari Veedhi",
    "Yata veedhi",
    "Fish Bazar Veedhi",
    "Pedawaltair village",
    "One World School area",
    "Nauka Nagar",
    "Prasantha Nagar",
    "SAi temple (opposite) Sivajipark area",
    "Six tap junction",
    "China Polamamba Temple area",
    "Samatha Hostel (AU)",
    "Karakachettu Polamamba Temple area"
  ],
  "21": [
    "Harbour Park road",
    "Pandurangapuram area",
    "Golden gate apartment area",
    "HPCL Quarters",
    "Sai Baba Temple area",
    "Kotak School area",
    "Kirlampudi lay out",
    "U Out gate down",
    "Lalithamma Temple area",
    "Peethalavariveedhi",
    "Defence flats",
    "Nethaji Veedhi",
    "Kona Veedhi",
    "Ommi Veedhi",
    "Masjid Back Side",
    "Tamil Street",
    "Relli Veedhi",
    "Church street",
    "Jagannatha temple area",
    "Old CBI Down",
    "GVMC Quarters",
    "Opposite 3-Town Police Station",
    "AU Campus",
    "Chinna Waltair part",
    "East PointColony part"
  ],
  "22": [
    "PEETHALA VANI PALEM",
    "- SEN A Sivajipalem",
    "Chinna Polamamba temple opposite",
    "Mangapuram colony area",
    "Anubhav School area",
    "Peethalavanipalem",
    "VUDA Quarters",
    "Kalabharathi opposite",
    "Peethapuram colony",
    "Maddilapalem main road",
    "New Resapuvanipalem",
    "Siddarthanagar vambay hosues",
    "Sri Krishna Temple back side area",
    "Varun Motors line",
    "AU ENgineering College Out gate area (Opp CMR Central)",
    "New Resapuvanipalem municipal school area",
    "AU Quarters (Engineering)",
    "Swarna Bharati Opposite",
    "Balajinagar",
    "Dutt island area",
    "VIP road (Tycoon hotel side) 23 3 23 SRI GUDLA VIJAYA SAI EENADU Main Road",
    "EENADU Backside",
    "Opp balayesu Church Seethammadhara",
    "State Bank Area",
    "Yechuri Aprt",
    "priyadarshini colony",
    "Vijaya Residency Area",
    "Venkateswara Swamy Temple Backside",
    "Near Burial Ground",
    "Ramavathar Convent Area",
    "Chaitanya Nagar",
    "Maddilapalem Sivalayam Backside",
    "KRM Colony park area",
    "Auto Motors",
    "Maddilapalem Backside",
    "open well area",
    "Chaitanyanagar",
    "Renuka Aprt",
    "opposite Kanakamma Temple Backside and Beside",
    "New Durga Devi Temple opposite",
    "Kinnera Theater Backside",
    "Vevekananda Park",
    "SFS School area",
    "Ganesh babu hospital road lane",
    "75'-0\" road (Sri Sai ganesh guest house lane)"
  ],
  "24": [
    "Kranthi Nagar",
    "Nakkavanipalem",
    "Shivalayam Street 60 feet road",
    "Old Resapuvanipalem",
    "CMR Centre Back Side",
    "Tulasipeta",
    "Ramatalkies road",
    "Vinayaka nagar",
    "Gandhi Nagar",
    "Eenadu Main road",
    "P&T Colony",
    "TPT Colony",
    "AMG area. Ganesh nagar part",
    "Relliveedhi behind Wipro"
  ],
  "25": [
    "SEETHAMPETA MAIN Madhura Nagar",
    "Chakali Gedda",
    "Seethammpeta Vinayaka Temple area",
    "Shantipuram",
    "Sai Baba Temple area",
    "Ganesh Nagar part",
    "Krishna Temple Area",
    "Kanakammavari Veedhi",
    "Rajendra Nagar",
    "Apoorva Hospital Road",
    "MCV Primary School lane",
    "80 feet Road"
  ],
  "26": [
    "Lalitha Nagar",
    "Gnana Nikethan School Road",
    "Green Tulasi Appt.Road",
    "PNR Complex Road",
    "Krishna Hospital Road",
    "Chinnuru (Turakapalem)",
    "Mosque",
    "80 feet Road",
    "Near Jaggarao Bridge",
    "Sakshi Office Line",
    "BVK School Road",
    "Lilitha Appt. Road",
    "Gajana Appartment",
    "Near Tonda Ganapathi Temple",
    "Lalitha Pioneer Club Road",
    "Lalitha Temple Back Side Road",
    "Jindal Ply wood Beside Road",
    "Union Bank of India Road",
    "Priyadarshini Paradise Back Side",
    "Vijay Kunj Appt.Road",
    "St. Marry School",
    "Akkayapalem",
    "Vagdevi School Road",
    "NGGO's Colony",
    "80 Feet Road",
    "Opp Sai baba Temple",
    "N.T. School Road",
    "Opp Venugopalaswamy Temple",
    "V C Bank",
    "ICWAZ Bhavan",
    "Ramakrishna Nagar Near Bazar",
    "Near Sai Baba Temple"
  ],
  "27": [
    "VIP Road",
    "Commissioner Bunglow Opposite road",
    "Rama Talkies road",
    "Amar Nagar",
    "Timpany School area",
    "CBM Compound area",
    "Sampath Vinayak Temple area",
    "Srinagar",
    "Ashok Nagar",
    "E-Seva Back side",
    "Bhagatsingh Colony",
    "Kumari Veedhi",
    "Chakalipeta",
    "Dondaparthi",
    "Mandavari Veedhi",
    "Akkayapalem road",
    "Old Sree Surya road",
    "Nehru Bazar road",
    "Kala Hospital road",
    "Ramalayam area",
    "Reddy hospital road"
  ],
  "28": [
    "Circuit House",
    "Daspalla Hills",
    "Harbour Quarters Park",
    "Ram Nagar",
    "Pitandibba",
    "Kailasametta",
    "Bhanoji Nagar",
    "Nehru Nagar"
  ],
  "29": [
    "Kannayyapeta",
    "Apsara Main Road",
    "Prakasha Rao Peta",
    "Anthony Nagar",
    "Chandaka Veedhi",
    "Prahladha Kalyanamandapam Road",
    "Durga Hospital Road",
    "Beach Road",
    "Otagedda",
    "Dandu Bazar",
    "Angadi Dibba & Jagadamba Road",
    "Venkatapathiraju nagar"
  ],
  "30": [
    "Old Employment Office",
    "Kotta Jalaripeta",
    "KGH opp",
    "Jalaripeta",
    "Kodipandelavari Street",
    "Kummara Veedhi",
    "Salipeta",
    "Kotta Salipeta",
    "Chakali Veedhi",
    "Super Bazar Area",
    "Paindorapeta Road",
    "ZP Road",
    "Surya Hospital Road",
    "Krishna Nagar",
    "AU Ladies Hostel Road"
  ],
  "31": [
    "YSRC P Bheem Nagar",
    "South Jail Road",
    "Assam Gardens",
    "Krishna Gardens",
    "II Town PS Down",
    "Dabagardens",
    "Yellammathota",
    "Suryabagh",
    "Kanakala Dibba",
    "Boddu Naidu Thota",
    "APSRTC Complex",
    "Lalitha Colony",
    "Gollalapalem",
    "SBI Colony",
    "Prakasarao Peta",
    "Spring Road & 75 feet Road"
  ],
  "32": [
    "South Jail Road",
    "Nerella Koneru Road",
    "Allipuram Road",
    "Karanala Veedhi",
    "Chakrathota",
    "Railway Quarters",
    "Devangula Veedhi",
    "Krishna Veedhi",
    "Pootivarimanyam & Bheem Nagar",
    "Krishnanagar"
  ],
  "33": [
    "South Jail Road",
    "Kummari Veedhi",
    "Bangaramma Metta",
    "Harijana Veedhi",
    "Venkateswara Metta",
    "Sai Baba Street",
    "Dabagardens",
    "Leela Mahal Road",
    "Neelamma Vepa Chettu Road & Geeth Sangeeth Road"
  ],
  "34": [
    "SRMT Road",
    "Jandachettu",
    "Ambedkar Colony",
    "Netaji Nagar",
    "Atchiyamma Peta",
    "Kobbarithota",
    "Bhupesh Nagar & Taraka Rama Colony",
    "Chaluvathota part"
  ],
  "35": [
    "D.N.8-42-16",
    "THAMILA VEEDHI",
    "CHINNA Stadium Road",
    "Prasad Gardens",
    "Periki Veedhi",
    "Poolasandhu",
    "Velampeta",
    "Kallupakalu & 75 feet Road",
    "Gajula veedhi",
    "Panda veedhi"
  ],
  "36": [
    "Agraharam Veedhi",
    "Sunnapu Veedhi",
    "Kotta Road down",
    "Chengalaraopeta",
    "AVN College Down",
    "Godarigothulu",
    "SKML Strret",
    "Manthavari Strret",
    "Rangireeju Veedhi",
    "Down Relli Veedhi",
    "Upper Relli Veedhi",
    "Relli Veedhi",
    "Rajaka veedhi & Town Main Road"
  ],
  "37": [
    "Relli Veedhi",
    "Paindorapeta",
    "Asipapa Veedhi",
    "Kotta Relli Veedhi",
    "Chattalavri Veedhi",
    "Kotta Agraharamveedhi",
    "Agraharam Veedhi & Chengalaraopeta",
    "Gollaveedhi"
  ],
  "38": [
    "Agraharam Veedhi",
    "Chengalaraopeta",
    "Bukka Veedhi",
    "Kanchara Veedhi",
    "Town Hall Road",
    "SKML Strret",
    "Pappula Veedhi",
    "Gangabattula Veedhi",
    "Jilledamudivari Veedhi",
    "Chinnammavari Veedhi",
    "Shivalayam Street",
    "Thomson Street",
    "Beach Road",
    "Soldier Peta",
    "town Main Road & St.Alloy's High School Road",
    "Conveyor belt slum"
  ],
  "39": [
    "Thomson Street",
    "Conveyor Belt",
    "Kota Veedhi",
    "Potti Sriramulu Park",
    "Nallavari Street",
    "Kurpam Market",
    "Chagantivari Street",
    "Vada Veedhi",
    "Chilakapeta",
    "Padma Nagar",
    "Taraka Rama Nagar & Rama Krishna Nagar",
    "Ferry road"
  ],
  "40": [],
  "41": [
    "Jaganadhapuram",
    "Babu Colony",
    "Gedda Veedhi",
    "Gnanapuram Scheme Houses",
    "Konda Veedhi",
    "Manual Street",
    "Post office street",
    "R.C.Aided School Area",
    "Near St.Peters Play Ground",
    "Railway New Colony",
    "Railway Grounds",
    "Seva"
  ],
  "42": [
    "THATICHETLAPALEM"
  ],
  "43": [
    "Akkayyapalem 80 Feet road",
    "Chekkuduraya Building",
    "HP Gas Godown",
    "K V Quarters",
    "Munasabu Gari Colony",
    "Nandagirinagar",
    "Narendra Colony",
    "Vivekananda Hospital Road",
    "Yelamanchili Vari Street"
  ],
  "44": [
    "Santoshi Matha Temple",
    "Abid Nagar",
    "Akkayapalem Highway",
    "Andhra Jyothi",
    "Dadi Ram Murthy Kalyanamandapam",
    "Gavara Thatichetlapalem",
    "Gowri Kalyana Mandapam",
    "K V Quarters",
    "Madeti Gardens",
    "Muslim Thatichetlapalem",
    "Shadhikhana",
    "Srinivasa Nagar"
  ],
  "45": [
    "ASR Nagar"
  ],
  "46": [
    "4TH TOWN POLICE STATION",
    "SEETHAMMADHARA"
  ],
  "47": [],
  "48": [
    "ASR Nagar",
    "Bapuji Nagar",
    "Indira Nagar - I",
    "Indira Nagar - II",
    "Indira Nagar - IV",
    "Indira Nagar-V",
    "Jai Bharat Nagar",
    "Palnati Colony",
    "Pedda Kotturu",
    "Shivalingapuram",
    "Srinivasa Nagar"
  ],
  "49": [
    "VIGNESWARA APARTMENT - 1",
    "PR GARDENS",
    "Kamakshi Nagar",
    "Burma Camp",
    "ASR Nagar",
    "Lal Bahadur Nagar",
    "Burma Colony",
    "Girija Nagar",
    "Manikyamba Colony",
    "Chakali Gedda",
    "Manchu Konda Thota",
    "Satya Nagar",
    "Surya Nagar",
    "Ayyappa Nagar",
    "P.R.Gardens",
    "Nehru Nagar",
    "Ajay Kalam"
  ],
  "50": [
    "Manchu Konda Thota",
    "Murali Nagar",
    "Singaraya Metta",
    "Sai Ram Nagar",
    "Tenneti Nagar",
    "Madhavadhara",
    "Vidya Nagar",
    "Kalinga Nagar",
    "Seethanna Gardens",
    "Madhavadhara Manyam",
    "Murali Nagar Estate"
  ],
  "51": [
    "Madhavadhara",
    "Seethanna Gardens",
    "Kalinga Nagar",
    "Vidya Nagar",
    "Gold Smith Colony",
    "Appayya Nagar",
    "Citti Babu Colony",
    "Mahat Colony",
    "Bheem Nagar",
    "Gandhi Nagar",
    "Eklavya Colony",
    "R & B Colony",
    "Madhavadhara Vuda Colony",
    "Ambedkar Colony"
  ],
  "52": [
    "Air Port & New Police Quarters",
    "Durga Puram",
    "Ganesh Nagar",
    "Gowri Nagar",
    "Guruda Colony & Ambedkar Nagar",
    "Marripalem Vuda Layout",
    "New Karasa",
    "Old Karasa",
    "Old Police Quarters",
    "Netaji Colony"
  ],
  "53": [
    "Bhaskar Gardens",
    "Rana Pratap Nagar",
    "Golla Veedhi",
    "Masjaid Veedhi",
    "Andhra Kesari Nagar",
    "Harsha Nagar",
    "Parvathi Nagar",
    "Jakhir Hussain Nagar",
    "Maharani Veedhi",
    "Gavara Veedhi",
    "Marripalem",
    "Marripalem Main Road",
    "Parvathi Nagar - I"
  ],
  "54": [
    "104 Area Main Road",
    "Bapuji Nagar",
    "Gajapathinagar",
    "Golla Veedhi",
    "Gavara Veedhi",
    "Jyothi Nagar",
    "Lakshmi Nagar",
    "Kancharapalem Main Raod",
    "Maharani Veedhi",
    "Nalanda Nagar",
    "Old Police Station Area",
    "Ravindranagar",
    "Reddy Kancharapalem"
  ],
  "55": [
    "SASIKALA",
    "D.No.49-53-10/9(17)",
    "Jashuvanagar",
    "Ashokngar",
    "Kothawada Veedhi",
    "Reddy Kancharapalem",
    "Bapuji nagar",
    "Devendranagar",
    "Opp Mini Sweage Farm",
    "Near Ramalayam Temple",
    "Thatichetlpalem Bus Stop",
    "Kapparada",
    "Kancharapalem",
    "Jogarao Nagar",
    "Ashok"
  ],
  "56": [
    "Dayanand nagar",
    "Durga Nagar",
    "Gavara Kancharapalem",
    "Golla Kancharapalem",
    "Kancharapalem Main Raod",
    "Malla Suri Veedhi",
    "NDA AREA",
    "Railway Quarters",
    "Meghadripeta defence colony"
  ],
  "57": [
    "Asivanipalem",
    "Bharat Nagar",
    "Bhavani Gardens",
    "Durga Puram",
    "Gowri Nagar",
    "Marripalem",
    "MES Quarters",
    "KV No : 1 & 2 Staff Quarters",
    "NAD Civilians Residential Colony",
    "NAD Colony",
    "Nirman Park",
    "Ramu Naidu Colony",
    "Marripalem Main Road",
    "Sakethapuram",
    "Siddardha Nagar",
    "Ganesh Nagar",
    "Sri Ram Nagar",
    "Subash Nagar",
    "Syam Prasad Nagar",
    "Thummadapalem"
  ],
  "58": [
    "MALKAPURAM POST Ajantha Colony",
    "Annamma Colony",
    "Annapurna Nagar",
    "Ganesh Vani Palem",
    "Gollapalem",
    "Kodipandela Dibba",
    "Kunchalamma Veedhi",
    "Kunchumamba Colony",
    "Mulagada",
    "Old Ramalayam",
    "Pilakavani Palem"
  ],
  "59": [
    "Ashok Nagar Colony",
    "Checkpost",
    "Ex Serviceman Colony",
    "Ganapathi Nagar",
    "Hanuman Nagar",
    "Himachal Nagar",
    "Himachal Nagar( Zinc Gate)",
    "Kotha Nakkavanipalem",
    "Mulagada Housing Colony",
    "Nakkavani Palem",
    "Nehru Nagar"
  ],
  "60": [
    "Ashok Nagar",
    "Burma Colony",
    "Ganesh Mandir Street",
    "Hanuman Sanjeev Colony",
    "Indira Colony",
    "Janatha Colony part",
    "Jawahar"
  ],
  "61": [
    "RAMAKRISHNAPURAM",
    "MALKAPURAM"
  ],
  "62": [
    "Achi Naidu Thota",
    "Ambedkar Colony",
    "Asr Colony",
    "Cisf Quarters",
    "Coast Guard",
    "Durga Nagar Colony",
    "Gandhiji Street",
    "Harijana Veedhi",
    "Kranthi Nagar Upto Dr No 71-31- 584",
    "Nauseena Bagh",
    "Port Quarters"
  ],
  "63": [],
  "64": [
    "Yarada",
    "Gangavaram",
    "Jalaripeta",
    "Pallivedhi",
    "yathapalem",
    "Kongapalem",
    "Venkannapalem",
    "Godduvanipalem",
    "New Dibbapalem R.H colony",
    "Satyanarayanapuram"
  ],
  "65": [
    "Sanjeevagiricolony",
    "Bhanojithota",
    "Netaji Colony",
    "Sanjeeva Colony",
    "Vikas Nagar",
    "Priyadarshini Colony",
    "KL Rao Nagar",
    "Bhavani Bapuji colony"
  ],
  "66": [],
  "67": [
    "Ganesh Nagar",
    "New Gajuwaka",
    "Gajuwaka Main Road part",
    "High School Road",
    "Pentayya Nagar",
    "Krishna Nagar",
    "Jogavani Palem",
    "part",
    "Bojjanna Konda"
  ],
  "68": [
    "D.No. 2-25-17",
    "Akkireddy palem Main road Akkireddy Palem",
    "Panchavati",
    "Ram Nagar",
    "Mindi",
    "Gudivada Appanna Colony Part",
    "Kalika nagar",
    "Giriprasad Nagar",
    "Rajeev Nagar"
  ],
  "69": [
    "Chukkavaani palem",
    "Nathayyapalem",
    "Tunglam",
    "Tunglam SC Colony",
    "BHPV Township(BHEL)",
    "Harijana Jaggayyapalem",
    "Venkateswara Colony",
    "Sheela Nagar",
    "Venkatapathi raju nagar"
  ],
  "70": [
    "Chattivanipalem",
    "Pantulugarimeda part",
    "Pallavari Street",
    "Old Gajuwaka",
    "MMTC Colony",
    "Chittinaidu Colony",
    "Dasamikonda colony",
    "Drivers Colony",
    "TVN Colony",
    "LV Nagar",
    "LBS Nagar",
    "Srinivas Nagar",
    "Yerragedda Colony",
    "Sramikanagar part"
  ],
  "71": [
    "GAJUWAKA VIZAG -26 Auto Nagar",
    "Durga Nagar",
    "Sundarayya Colony",
    "Kunchamamba Colony",
    "Dattasai Nagar",
    "Visweswarayya Colony",
    "New Dibbapalem",
    "Gurunadha Rao colony",
    "Railway Quarters Vadlapudi",
    "Sramikanagar part",
    "Sri Nagar",
    "Sriram Nagar",
    "Thokada"
  ],
  "72": [
    "Chinagantyada SC Colony",
    "Chaitanya nagar",
    "Prasanthi Nagar",
    "Chinagantyada Mehar Nagar",
    "China Nadupuru",
    "Old Karnavani palem",
    "Sundarayya Colony Sri Nagar part",
    "Sri Nagar official Colony",
    "VUDA Colony",
    "Sri Nagar",
    "B.C. Social Welfare Colony",
    "Kanithi Road"
  ],
  "73": [
    "China Nadupuru part",
    "Gonthinavanipalem",
    "kailash Nagar",
    "Kotha Karnavani Palem",
    "Pydimamba Colony",
    "Sanath Nagar",
    "Seetha Ram"
  ],
  "74": [
    "Dallivanipalem",
    "Konavanipalem",
    "Dayal nagar",
    "Simhagiri Colony",
    "Peda korada"
  ],
  "75": [
    "Pedagantyada",
    "Patha Ayyannapalem",
    "Neelapuvedhi",
    "Musilinaidu Palem",
    "Mollivanipalem",
    "Nellimukku",
    "Ayyannapalem",
    "Durgavanipalem",
    "Seekuvanipalem",
    "Seetharam Nagaram",
    "Pedakorada",
    "Balacheruvu road"
  ],
  "76": [
    "Bala Cheruvu Sivalayam Veedhi",
    "Korada",
    "APHB Colony",
    "Samatha Nagar(2Blocks)",
    "ST Colony",
    "Ramachandra Nagar",
    "Rickshaw Colony",
    "Bharat Nagar",
    "Gopalareddy Nagar",
    "Swatantra Nagar",
    "Peda Nadupuru",
    "Seeravani Palem",
    "Dairy Colony",
    "Burma Colony",
    "Old karnavanipalem"
  ],
  "77": [
    "Goruduvanipalem",
    "Palikala Doddi",
    "Nammi Doddi",
    "Yalamanchili Doddi",
    "New Ginnipalem",
    "Old Ginnivanipalem",
    "Maddivanipalem",
    "Palavalasa",
    "Peda Devada",
    "Peddapalem",
    "Pittavanipalem",
    "Relangi Doddi",
    "Matta Doddi",
    "Butchayyapeta",
    "Madina Bagh",
    "Sattar Camp",
    "Sri ram Nagar",
    "Laxmi Nagar",
    "Chinapalem",
    "Pedapalem",
    "Islam Peta",
    "Mahammed Saheb Peta. Kanitinaidu Colony",
    "Steel Plant Sector-1&II",
    "CISF Quarters"
  ],
  "78": [],
  "79": [
    "Sivaji Nagar",
    "Gallavani Palem",
    "Old Aganampudi",
    "Santhi Nagar Satram",
    "Srinivasa Nagar",
    "Annapaurna Nagar",
    "K.S.N reddy Nagar",
    "Sanivada",
    "Lankelapalem karanam vari veedi",
    "B.C Colony",
    "Dasari Veedi",
    "S.C colony",
    "Konda Veedi",
    "Sri Ranga Nayakula Colony",
    "Kotturu Colony",
    "Appikonda vari Veedi",
    "Ganji Peta",
    "Pujari Vari veedi",
    "Golla peta",
    "Lankelapalem Industries",
    "Sai Nagar (Desapatrunipalem)",
    "Ashok Nagar",
    "Desapatruni palem",
    "Jajulavani palem",
    "Attavani palem",
    "Peda madaka part",
    "Kondayyavalasa part"
  ],
  "80": [
    "Tadi",
    "Rajupalem",
    "Valluru and parts of Gavarapalem pedda veedhi",
    "Santhoshimatha gudi veedhi",
    "Parameswari park road",
    "Chadaram veedhi",
    "Branch road",
    "Pallapu veedhi",
    "Dibba veedhi",
    "Budha Prakasarao vreedhi",
    "PVR Naidu veedhi",
    "Budh RamaDas gari veedhi",
    "Sathakampattu",
    "China ramaswamy gudi veedhi",
    "Dasarigedda Road",
    "Arundhati road",
    "Budha armadas street",
    "Demuni thota",
    "karri veedhi"
  ],
  "81": [
    "Parts of GNT Road",
    "Maszid road",
    "Kaspa veedhi",
    "Westren side of Ramalayam St",
    "One- Way Traffic Road",
    "Metarnaty Hospital Road",
    "Reddy Adi Narayana Veedhi",
    "nidanam Doddi",
    "GNT Road",
    "Botcha vari veedhi",
    "Sagi.Subba Raju gari veedhi",
    "Dadi BhogaLingam school veedhi",
    "Municipal Dispensary Road",
    "Dr.Appa Rao Road",
    "Kamakshamma Gudi area",
    "Raithu Sangham road",
    "Eastern side of 101 area",
    "Dadi Bhoga Lingam School area",
    "Dibba veedhi",
    "Villuri Parandhamayya gari veedhi",
    "Kobbari thota",
    "Nookalamma gudi veedhi",
    "Dadi vari veedhi",
    "Peda road",
    "Branch road",
    "Dhobi colony",
    "Thotada road",
    "Bhogalingswamy veedhi",
    "Thota veedhi",
    "market area",
    "Bandigadi veedhi"
  ],
  "82": [
    "Gandhi Nagar &Anjayya Colony & Income Tax St",
    "Post Office St",
    "Vijaya Ramaraju peta Parts of Eastren side of Pudimadaka road",
    "New colony area",
    "Baru vari veedhi",
    "GNT road",
    "Relli Veedhi",
    "One-Way traffic road Parts of Parasaramuni peta",
    "Sarada colony",
    "Pudimadaka road(Western side)",
    "Subbaram layoutcolony",
    "Teachers colony",
    "Bypass road",
    "Umalada road Parts of Narasinga rao peta",
    "Burma colony",
    "Telephone Exchange road",
    "Chodavaram road",
    "Chakali peta",
    "Railway Track side road and Chodavaram road areas. Community Hall areaand Railway Track side road area",
    "Sriramnagar and Madhavasadhan area",
    "Sarada river bund area"
  ],
  "83": [
    "Mirayala Colony",
    "ARC Quarters",
    "Lakshmideipeta",
    "Pathurudu Colony area Wood peta",
    "Sarvakamadamba park st",
    "Velpula Vedhi",
    "Chakala peta",
    "and Amanchivari veedhi",
    "Town Girls High School area",
    "Kondapalli vari St",
    "Nagavamsam St",
    "Takasi veedhi",
    "Loka vari veedhi& Malla veedhi area. Goods Shed Road",
    "Railway Station Road",
    "Gandhi Bomma Kudali part.Loka vari veedhi "
  ],
  "84": [
    "PIN CODE 531001 Takasi veedhi part",
    "Mallimadugula vari veedhi",
    "Nagavamsam veedhi part",
    "Pedda veedhi part",
    "Malla veedhi",
    "GNT Road",
    "Pedabhaskarayya peta",
    "Chinabhaskarayya peta",
    "Seelamanthula vari veedhi",
    "Thendra peta. Kotni veedhi",
    "Railway station Road Pilla vari Goorja part",
    "Neyyala veedhi part",
    "Peda Raju peta",
    "Golla veedhi parts. Neyyala veedhi",
    "Peda raju peta",
    "Perugubazar",
    "Fish market area",
    "Vizayanagaram Road",
    "Pilla vari gorja",
    "Ring Road",
    "Kuncha vari veedhi",
    "Koppaka",
    "KNR peta",
    "Sirasapalli.Salapuvanipalem"
  ],
  "85": [
    "\"PLOT NUM:166-167 PHARMACITY COLONY",
    "LEMARTHY AGRAHARAM AGANAMPUDI VIZAG 530046 Talariavanipalem",
    "Dibbapalem",
    "Mantripalem",
    "Kotturu",
    "Sri Ram colony",
    "Vinayaka Nagar colony",
    "Lankelapalem",
    "Gonna Vani palem",
    "E Marripalem",
    "Lemarthi colony",
    "Kotta palem",
    "E-Bonangi",
    "Payakarao peta(E-Marripalem)",
    "Peddi naidu palem",
    "Aganampudi",
    "Dhana Vari palem",
    "Andaman Kondayyavalasa",
    "Chati vanipalem",
    "Pedamadaka part",
    "Karri vani palem",
    "Sai nagar",
    "Bramaramba uppara colony",
    "B.C Colony",
    "Pinamadaka",
    "Donkada",
    "Pudi vani palem",
    "Aganampudi Kondayya valasa"
  ],
  "86": [
    "KURMANNAPALEM",
    "VADLAPUDI",
    "VIZAG-46 Uppara colony",
    "Satavahana Nagar Opp NH-16",
    "Lella koteswara rao street",
    "Duvvada station road",
    "BSNL office line",
    "Sai Baba temple street",
    "Pavani Public school opposite street",
    "Kurmannapalem",
    "ITI Road",
    "Yatha palem Phase-3",
    "Rajeev Nagar",
    "Rasalamma Colony",
    "VUDA Phase-I",
    "Matru Sree Nagar",
    "VUDA phase-V",
    "VUDA phase-VII",
    "Talarivani palem Part",
    "Duvvada Sector-II",
    "China Yathapalem",
    "Sairam Parlor Backside",
    "Rajulapalem kasipalem",
    "Simon Nagar",
    "Fakeerthakiya"
  ],
  "87": [
    "VADLAPUDI(POST)",
    "Kurmannapalem Part",
    "Vadlapudi R.H Colony",
    "Vadlapudi Kanithi Colony Main Road",
    "Vadlapudi Chakali street",
    "Vadlapudi Muslim street",
    "Old Vadlapudi",
    "Ganesh nagar",
    "Lakshmipuram Colony",
    "Gavara Veedhi",
    "Yadava Street",
    "Kalinga Street",
    "Telukala Street",
    "Appikonda colony",
    "Tirumala nagar",
    "Rajulapalem Part",
    "Siddarda Nagar",
    "Kurmannapalem road",
    "Gandhibomma Street",
    "Kanithi High School road",
    "TGR Nagar"
  ],
  "88": [
    "jaggarajupeta",
    "Kapu Jaggarajupeta",
    "Attavanipalem part",
    "Dockyard Colony",
    "BC Colony",
    "Karnavanipalem Aganampudi"
  ],
  "89": [
    "Chandra Nagar",
    "Adarsha Nagar",
    "Surya Nagar",
    "Appalanarasimha Colony",
    "Kharavela nagar",
    "Kothapalem",
    "Nagendra Nagar",
    "Santhosh Nagar",
    "Ganesh Nagar",
    "Pullambatla palem",
    "Santhoshimatha colony",
    "Boddeti Street",
    "Chakalaveedhi",
    "Main Road krishna nagar",
    "Gandhi Nagar",
    "Madhyaveedhi",
    "ramalayam Veedhi",
    "Yellapuvanipalem",
    "Bhagatsingh Nagar"
  ],
  "90": [
    "APSEB COLONY",
    "BUTCHIRAJU PALEM",
    "Vidyuth Nagar",
    "Seetharamarajunagar",
    "Susarla Colony",
    "Butchirajupalem",
    "main road",
    "APSEB Colony",
    "Gandhi Nagar",
    "Vinodh Nagar",
    "Lakshmi Nagar (E & F blocks)"
  ],
  "91": [
    "Lakshmi Nagar (C",
    "D blocks)",
    "Lakshmi Nagar",
    "Harijana Colony",
    "Vidya Nagar",
    "Butchirajupalem",
    "China Butchirajupalem",
    "Old Gopalapatnam"
  ],
  "92": [
    "SIVA DEVI",
    "DO.NO.14-7",
    "R.R.V.PURAM",
    "GOPALAPATNAM",
    "Venkatapuram",
    "RR Venkatapuram",
    "SC Colony",
    "Padmanabha Nagar",
    "Nandamuri Nagar",
    "Kamparapalem",
    "Sri Ram Nagar",
    "Bapuji Indira Nagar",
    "Community Hall",
    "Relli Veedhi",
    "Lakshmi Nagar",
    "Banta Colony"
  ],
  "93": [
    "RAO D.NO.8-58",
    "NAIDU THOTA",
    "VEPAGUNTA POST",
    "PENDURTHI",
    "Sai Durga Nagar",
    "Durga Nagar",
    "Krishna Nagar",
    "Balaji Gardens",
    "Prahaladhapuram",
    "Simhadri Nagar",
    "Dattasai Nagar",
    "Virat Nagar",
    "Maruthi Nagar",
    "Lanka Nagar",
    "Rajaji Marg",
    "Sai baba Temple area",
    "Prahaladhapuram Colony",
    "Port Quarters",
    "Pallinarayanapuram",
    "Anjanadri Colony",
    "Sai Madhava Nagar",
    "Sector-I",
    "Chandanapuri Colony",
    "Bharath Nagar",
    "Gollanarayanapuram",
    "Srinivasa Nagar",
    "Balaji"
  ],
  "94": [
    "Gangiredla Colony",
    "Anjaneyulu Nagar",
    "Appalanarasimham Colony",
    "Venkata Sai Nagar",
    "Banta Colony",
    "Ravi Nagar",
    "Sivalayam Colony",
    "Prasanthi Nagar",
    "Vidya Nagar",
    "Gowtham Nagar",
    "Mutyamamba Colony",
    "BC Colony",
    "Rajaka Veedhi",
    "Purushothapuram",
    "Gokuldham Colony",
    "BHPV Teachers Colony",
    "Sanathivanipalem",
    "Simhapuri Colony",
    "Phase-II",
    "Paidimamba Colony",
    "Krishna Nagar",
    "RR Venkatapuram",
    "Kalapallivari street",
    "Municipal Office Back side",
    "Naiduthota"
  ],
  "95": [
    "CHINNAMUSIDIWAD",
    "PENDURTHI",
    "MES Layout",
    "Cheemalapalli",
    "Porlupalem",
    "Gavara palem",
    "Seshadri Nagar",
    "Varalakshmi Nagar",
    "Santhosh Nagar",
    "BC Colony- Gavara palem",
    "SC BC Colony - Lakshmipuram",
    "Port Colony",
    "Rama Co-operative Colony",
    "HB Colony",
    "Gokuldham Colony",
    "Relliveedhi",
    "Krishnarayapuram",
    "Gollivillivanipalem",
    "LIC Colony",
    "Papayyarajupalem",
    "BC Colony",
    "Surya Nagar",
    "Port Colony-Go VN Colony",
    "SC Colony-Ramalayam Colony",
    "Rajaka Veedhi",
    "Lakshminarasimha Nagar",
    "Lakshminarasayyamma Nagar",
    "NAD Layout",
    "Ratnagiri Nagar",
    "Satabdhi Nagar"
  ],
  "96": [
    "Pendurthi old Village",
    "Telakalaveedhi",
    "Z.P. HS area",
    "Prasanthi Nagar",
    "Yethapeta",
    "Sai Nagar",
    "Adityanagar",
    "Port Colony",
    "Mondibanda"
  ],
  "97": [
    "CHINNAMUSIDIWADA",
    "PENDURTHI",
    "Kranthi Nagar",
    "VUDA Colony",
    "Railway Colony",
    "Prasanthi Nagar",
    "Savithri Nagar",
    "Ambedkar Nagar",
    "Srinivasa Nagar",
    "Ganesh Nagar",
    "saradha nagar",
    "BRTS Road",
    "Sapthagiri Nagar",
    "Hamsi Nagar",
    "Sujatha Nagar",
    "A-Zone",
    "Sujatha Nagar B-Zone",
    "Sujatha Nagar C1 Zone",
    "C2 Zone",
    "Anjaneya Nagar",
    "Gopala Krishna Nagar",
    "Karmika Nagar",
    "Giriprasad Nagar",
    "Subhadra Gardens",
    "Venkatadri 3",
    "5 & 6 layouts",
    "Satya Nagar",
    "Ashok Nagar",
    "Dronam rajunagar",
    "Lakshmi Nagar",
    "Vidya Nagar",
    "Seshadri Nagar",
    "Chinamushidiwada",
    "Chakalaveedhi",
    "Sai Baba Veedhi",
    "Panchyat Shop rooms",
    "Durga Nagar",
    "Naravanipalem",
    "Water Tank",
    "Gayathri"
  ],
  "98": [
    "SIMHACHALAM",
    "Appannapalem",
    "Simhapuri Layout",
    "Adivivaram",
    "SC Colony",
    "Old Adivivaram",
    "Landagaruvu",
    "MMTC Colony",
    "Gandhi Nagar",
    "Gantala veedhi",
    "Kapuveedhi",
    "Rajulavedhi",
    "Pushkariniveedhi",
    "Santhoshimatha Temple",
    "Priya Gardens",
    "Sai Nagar",
    "Pydithallamma Temple",
    "Lower Gosala",
    "AMG Hospital",
    "Ghot Road",
    "Simhachalam Hill",
    "Srinivasa Kalyanamandapam",
    "Sai Baba Temple Street",
    "Shipyard Layout",
    "Priyagardens",
    "Balaji nagar up",
    "Sai Madhava Nagar",
    "Sector-2"
  ]
};

const AREA_TO_WARD = {
  "bunglow metta": 1,
  "vempadavariveedhi": 1,
  "kapuveedhi": 1,
  "kondapeta": 1,
  "kondapeta colony": 1,
  "alankavariveedhi": 1,
  "wilsonpeta": 1,
  "wilson peta company quarters": 1,
  "jutemill quarters & zp high school": 1,
  "kothapeta vani school area": 1,
  "reddika veedhi": 1,
  "bogguroad": 1,
  "perikiveedhi- chiilla peta": 1,
  "parimi thammayya lane": 1,
  "thippana vari veedhi": 1,
  "kuncham apprao street": 1,
  "chinthalapudi apparao street": 1,
  "jogavari veedhi": 1,
  "local office road": 1,
  "thata theatre area": 1,
  "kusumuri vari veedhi and yellamma gudi area": 1,
  "ramannapeta": 1,
  "nagarapuveedhi": 1,
  "balaji": 1,
  "sabbivanipeta": 2,
  "esi hospital quarters": 2,
  "grandhalayam veedhi": 2,
  "vuda complex": 2,
  "konda area": 2,
  "satyanarayana peta market road": 2,
  "hospital": 2,
  "ramalayam temple area.ntr kalyna mandapam": 2,
  "venkateswara theatre to bora guruvula reddy street": 2,
  "kummari jeerupeta": 2,
  "chillapeta": 2,
  "keetin peta church area": 2,
  "mini stadium": 2,
  "pallikummaripalem": 2,
  "rayipalem": 2,
  "rajalingampeta": 2,
  "yathakummaripalem": 2,
  "gorinta poultries area": 2,
  "amg area": 2,
  "muslims thota": 2,
  "relliveedhi": 2,
  "mamidipalem": 2,
  "dekkatipalem": 2,
  "guruvu gari thota area": 2,
  "nammivanipeta colony": 2,
  "nammivanipeta": 2,
  "koradapeta": 2,
  "jeerupeta": 2,
  "karri nammi vanipeta": 2,
  "pasi barli vari kallalu": 2,
  "edadhasaripeta": 2,
  "chakali peta": 2,
  "akkaramani ramunaidu house area": 2,
  "sangivalasa colony": 2,
  "sangivalasa": 2,
  "valadhapeta part": 2,
  "telephone exchange area": 3,
  "medharavedhi": 3,
  "thotaveedhi": 3,
  "2nd ward front of the mup school": 3,
  "cinema hall area": 3,
  "dutch road": 3,
  "old iti": 3,
  "kummaripalem road": 3,
  "gaduveedhi": 3,
  "mdo office quarters veedhi": 3,
  "krishnayya veedhi": 3,
  "saraswathi samajam": 3,
  "gantasthambham area.scavangers colony relliveedhi": 3,
  "burma colony": 3,
  "smith street": 3,
  "nalli veedhi": 3,
  "sai baba temple": 3,
  "subhash road": 3,
  "gedda veedhi": 3,
  "maseedh area": 3,
  "st. anns grounds": 3,
  "bank road": 3,
  "appikonda veedhi": 3,
  "vaddipolamma gudi area": 3,
  "kallaveedhi": 3,
  "nehru school area": 3,
  "chilakavariveedhi": 3,
  "lankadavari veedhi": 3,
  "old bus stand area": 3,
  "cbm school": 3,
  "bukkidora meda": 3,
  "nehru street": 3,
  "ab chruch area area": 3,
  "reddikaveedhi": 3,
  "municipal high school area": 3,
  "golla veedhi": 3,
  "kanyakaparameswara gudi veedhi": 3,
  "motilal veedhi": 3,
  "yatha veedhi": 3,
  "pandaveedhi": 3,
  "sivalyam temple area": 3,
  "nookalamma gudi veedhi": 3,
  "narasimha swamy temple road": 3,
  "bramhana veedhi": 3,
  "boyiveedhi": 3,
  "court area": 3,
  "narasimha swamy temple area": 3,
  "golla street": 3,
  "ntr colony": 3,
  "sub - registrer office area": 3,
  "diet area": 3,
  "govt. hospital area": 3,
  "mangala veedhi": 3,
  "yeguvapeta": 3,
  "srihari gari house area": 3,
  "police quarters area": 3,
  "kothapeta tank area": 3,
  "zp guest housearea": 3,
  "nerella valasa colony": 3,
  "residential school area": 3,
  "beach road": 3,
  "nerellavalasa hill area (og)": 3,
  "gadu veedhi": 3,
  "konkiveedhi": 3,
  "ganagalla vari veedhi": 3,
  "durga ashramma area": 3,
  "hostel area": 3,
  "krishna colony": 3,
  "gollapalem": 3,
  "boyyipalem junction": 5,
  "paradesi palem": 5,
  "ews colony": 5,
  "jk layout": 5,
  "ambedkar colony": 5,
  "boravanipalem": 5,
  "marikavalasa ngo's drivers colony": 5,
  "kommadi village": 5,
  "kommadi": 5,
  "kommadi sc colony": 5,
  "sai ram colony": 5,
  "amrutha arcade": 5,
  "nagarampalem village": 5,
  "carpenter colony": 5,
  "swayamkrushi nagar": 5,
  "ayyappa nagar": 5,
  "vivekananda colony": 5,
  "vikalangula colony": 5,
  "ganeshnagar road": 5,
  "dockyard colony": 5,
  "bottavanipalem": 5,
  "sadguru sai colony": 5,
  "sri laxmi nagar": 5,
  "siva shakti nagar": 5,
  "paradesipalem": 5,
  "marikavalasa hill": 5,
  "rajeev gruha kalpa type-i": 5,
  "nr. techno school": 5,
  "rajeev gruha kalpa type-ii": 5,
  "rajeev gruha kalpa": 5,
  "near marikavalasa": 5,
  "car shed junction": 6,
  "laxmivanipalem": 6,
  "rh colony": 6,
  "usmania colony": 6,
  "hb colony": 6,
  "ashok nagar": 6,
  "ratana residency": 6,
  "anand residency": 6,
  "bakkannapalem": 6,
  "fci layout": 6,
  "gayatri nagar": 6,
  "sai priya garden": 6,
  "chandrampalem": 6,
  "madhurawada junction": 6,
  "bhagavandas colony": 6,
  "kommadi junction & vasantha vihar": 6,
  "siddardha nagar": 6,
  "gcc layout": 6,
  "srinivasa nagar": 6,
  "devimetta": 6,
  "vambay colony (blocks) 1a": 7,
  "krishna nagar": 7,
  "port colony": 7,
  "sub-registrar area": 7,
  "kalanagar": 7,
  "mallayyapalem": 7,
  "mallayyapalem sc colony": 7,
  "skml layout": 7,
  "vambay colony a": 7,
  "z vambay colony 20aa to 24a vambay colony 24b to 26b": 7,
  "27a to 29b": 7,
  "34a to 36a": 7,
  "36b to 40b": 7,
  "41a to 44a": 7,
  "44b to 47 b": 7,
  "priyadarsini colony": 7,
  "dhobi colony": 7,
  "tailors colony": 7,
  "madhurawada jn": 7,
  "bapujinagar": 7,
  "swatantra nagar": 7,
  "dobhi colony": 7,
  "shyam nagar": 7,
  "srinivas nagar": 7,
  "ayodhya nagar": 7,
  "timmapuram": 7,
  "ap hb colony": 7,
  "mithilapuri vuda colony": 7,
  "old madhurawada": 7,
  "rtc colony": 7,
  "manam anjaneyulu colony": 7,
  "law college": 8,
  "chanukyapuri layout": 8,
  "sundarnagar": 8,
  "tarakaramanagar": 8,
  "p.k.palem": 8,
  "old pm palem": 8,
  "ramaraju enclave": 8,
  "vikalangual colony": 8,
  "ap revenue layout": 8,
  "musalayyapalem": 8,
  "gudlavanipalem": 8,
  "sagarnagar hig-1": 8,
  "sagarnagar hig-ii hig-ia & mig-a": 8,
  "sagarnagar mig-a": 8,
  "sagarnagar mig-b": 8,
  "sagarnagar mig-d": 8,
  "sagarnagar lig-a": 8,
  "sagarnagar lig- b": 8,
  "sagarnagar lig-c": 8,
  "thatichetlapalem": 8,
  "bhuvaneswari colony": 8,
  "subhash sirigudi nagar": 8,
  "gollala yendada": 8,
  "mubarak colony": 8,
  "chinna rushikonda": 8,
  "chinna rushikonda ommivanipalem": 8,
  "peda rushikonda swarna bharathi nagar": 8,
  "swarna bharathi nagar": 8,
  "sb nagar": 8,
  "durga nagar": 8,
  "chandram palem village ngo's layout": 8,
  "jodugullapalem": 9,
  "visalakshinagar": 9,
  "ramalayam street": 9,
  "sanjay nagar": 9,
  "sanjeev nagar colony": 9,
  "sc &st colony": 9,
  "visalakshi nagar": 9,
  "chalapti nagar": 9,
  "dayal nagar": 9,
  "police quarters": 9,
  "dairy farm": 9,
  "thotagaruvu": 10,
  "raveendra nagar -ii": 11,
  "srihari nagar": 11,
  "gandhi nagar": 11,
  "vivekananda nagar": 11,
  "priyadarshini nagar": 11,
  "priyadarshini colony": 11,
  "balaji nagar": 11,
  "anna nagar. thotagaruvu": 11,
  "sri ram nagar": 11,
  "arilova sector-i": 11,
  "kranthi nagar - i &ii": 11,
  "kranthi nagar st colony": 11,
  "mayuri nagar": 11,
  "btr nagar & bc colony": 11,
  "apsara colony & bharat nagar": 11,
  "bharath nagar & mustapha colony": 11,
  "mustapha colony": 11,
  "madhu hill view residency": 11,
  "aprasa colony -ii & drivers colony": 11,
  "swamy vivekananda nagar & rajiv nagar": 11,
  "tsi point": 11,
  "srinivasa residency & devi towers": 11,
  "ravindra nagar": 11,
  "sig nagar": 11,
  "rajiv nagar & central prison": 12,
  "surya teja nagar": 12,
  "parvathi nagar": 12,
  "btr nagar": 12,
  "nehru nagar": 12,
  "leela sundar nagar": 12,
  "ambedkar new colony": 12,
  "durga nagar & ambedkar nagar": 12,
  "durga nagar & sundarayya nagar": 12,
  "durga nagar & parvathi": 12,
  "sundarayya nagar": 13,
  "verni durga nagar": 13,
  "vishnupuri colony": 13,
  "siva sankar nagar": 13,
  "bhagatsingh nagar": 13,
  "sivaji nagar - i": 13,
  "nmr colony": 13,
  "durga bazar": 13,
  "sai nagar": 13,
  "asr nagar": 13,
  "laxmi nagar": 13,
  "pandurangapuram": 13,
  "operation colony": 13,
  "skml nagar": 13,
  "jai bheem nagar": 13,
  "laxmi parvathi nagar": 13,
  "sivaji nagar": 13,
  "srikrishna puram": 13,
  "pineapple colony": 13,
  "central prison area": 13,
  "mk’s kodandaramayya enclave": 14,
  "madhura backside": 14,
  "divya sakthi apartment line": 14,
  "vidyuthnagar": 14,
  "near port ground westside": 14,
  "near velama bhavanam": 14,
  "near swarna residents": 14,
  "near sampath villas aprt": 14,
  "b s layout": 14,
  "raghavendra nursing home area": 14,
  "andhra bank atm opposite": 14,
  "presidential school area": 14,
  "near more super market": 14,
  "kshatriya kalyana mandapam": 14,
  "bilal colony": 14,
  "seethammadhara junction": 15,
  "apseb colony": 15,
  "doctors colony": 15,
  "ambedkar nagar": 15,
  "vuda apts": 15,
  "lic qtrs": 15,
  "mmtc colony": 15,
  "h.b.colony steel plant qtrs": 15,
  "(part)": 15,
  "simhadripuram up area": 15,
  "durganagar": 15,
  "j r nagar": 15,
  "sivasenkari nagar": 15,
  "old venkojipalem": 15,
  "uma nagar": 15,
  "adarshnagar": 15,
  "lakshmi narasimha nagar": 15,
  "steel plant quarters(part)": 16,
  "krm colony part": 16,
  "shivalalyam opposite": 16,
  "chakalipeta": 16,
  "maddilapalem backside": 16,
  "bhanunagar": 16,
  "krishna college back side": 16,
  "go colony": 16,
  "isukathota village": 16,
  "maddilapalem bazar road": 16,
  "sc colony": 16,
  "kotha venkojipalem": 17,
  "housing board office area": 17,
  "teja apartment backside": 17,
  "near sanjeeva hospital": 17,
  "sector-1 mvp colony": 17,
  "near veera brhammam temple": 17,
  "sector 4 mvp colony": 17,
  "near isukathota petrol bunk backside": 17,
  "girijana bhavan area sector- 5 mvp colony": 17,
  "sdah high school area sector-5 mvp colony": 17,
  "near aqj central office": 17,
  "state bank colony and sector-8 mvp colony": 17,
  "opp: sarvani sweets": 17,
  "satyasai school area": 17,
  "ttd kalyanamandapam opposite area": 17,
  "lakshmi nagar": 17,
  "aadarsha nagar": 17,
  "ramalakshmi aprt": 17,
  "indira nagar": 17,
  "pedawaltair": 17,
  "beside ranga residency": 17,
  "yeeta peta": 17,
  "pedawaltair village": 17,
  "ratna nivas": 17,
  "dallivani veedi": 17,
  "fish market road": 17,
  "sulab complex": 17,
  "vizayanagar colony": 17,
  "padmanabha apartment": 17,
  "samatha college area": 18,
  "mvp sector- 9 & 10": 18,
  "kailashagiri konda route lane": 18,
  "relli veedhi": 18,
  "fishermen colony": 18,
  "muvvalavanipalem": 18,
  "vasavanipalem": 18,
  "a s raja ground area": 18,
  "mvp sector 2": 18,
  "& 7 area": 18,
  "cancer hospital area": 18,
  "sivaganesh nagar": 18,
  "mvp sector-12": 19,
  "opp: a s raja ground": 19,
  "mvp sector-11": 19,
  "gedda beside line": 19,
  "ushodaya main road to gedda line": 19,
  "ushodaya main road to nandhi temple backside": 19,
  "opp kkr gowtham school lawsonsbay colony": 19,
  "sri krishna chaitanya gurukula asramam": 19,
  "opp: post office": 19,
  "opp:santhi asramam": 19,
  "opp: md yathra nivas": 19,
  "vasuvanipalem": 19,
  "jalaripeta": 19,
  "gollalapalem": 20,
  "bhemunipatnma-531163 peawaltari junction": 20,
  "swati petrol bunk area": 20,
  "visakha eye hospital area": 20,
  "vijayanagar palace layout area": 20,
  "shramika nagar": 20,
  "nethaji veedhi chinawaltair": 20,
  "rajaka veedhi": 20,
  "kanakammavari gudi area": 20,
  "east point colony": 20,
  "kagitalavari veedhi": 20,
  "palikalavari veedhi": 20,
  "yata veedhi": 20,
  "fish bazar veedhi": 20,
  "one world school area": 20,
  "nauka nagar": 20,
  "prasantha nagar": 20,
  "sai temple (opposite) sivajipark area": 20,
  "six tap junction": 20,
  "china polamamba temple area": 20,
  "samatha hostel (au)": 20,
  "karakachettu polamamba temple area": 20,
  "harbour park road": 21,
  "pandurangapuram area": 21,
  "golden gate apartment area": 21,
  "hpcl quarters": 21,
  "sai baba temple area": 21,
  "kotak school area": 21,
  "kirlampudi lay out": 21,
  "u out gate down": 21,
  "lalithamma temple area": 21,
  "peethalavariveedhi": 21,
  "defence flats": 21,
  "nethaji veedhi": 21,
  "kona veedhi": 21,
  "ommi veedhi": 21,
  "masjid back side": 21,
  "tamil street": 21,
  "church street": 21,
  "jagannatha temple area": 21,
  "old cbi down": 21,
  "gvmc quarters": 21,
  "opposite 3-town police station": 21,
  "au campus": 21,
  "chinna waltair part": 21,
  "east pointcolony part": 21,
  "peethala vani palem": 22,
  "- sen a sivajipalem": 22,
  "chinna polamamba temple opposite": 22,
  "mangapuram colony area": 22,
  "anubhav school area": 22,
  "peethalavanipalem": 22,
  "vuda quarters": 22,
  "kalabharathi opposite": 22,
  "peethapuram colony": 22,
  "maddilapalem main road": 22,
  "new resapuvanipalem": 22,
  "siddarthanagar vambay hosues": 22,
  "sri krishna temple back side area": 22,
  "varun motors line": 22,
  "au engineering college out gate area (opp cmr central)": 22,
  "new resapuvanipalem municipal school area": 22,
  "au quarters (engineering)": 22,
  "swarna bharati opposite": 22,
  "balajinagar": 22,
  "dutt island area": 22,
  "vip road (tycoon hotel side) 23 3 23 sri gudla vijaya sai eenadu main road": 22,
  "eenadu backside": 22,
  "opp balayesu church seethammadhara": 22,
  "state bank area": 22,
  "yechuri aprt": 22,
  "vijaya residency area": 22,
  "venkateswara swamy temple backside": 22,
  "near burial ground": 22,
  "ramavathar convent area": 22,
  "chaitanya nagar": 22,
  "maddilapalem sivalayam backside": 22,
  "krm colony park area": 22,
  "auto motors": 22,
  "open well area": 22,
  "chaitanyanagar": 22,
  "renuka aprt": 22,
  "opposite kanakamma temple backside and beside": 22,
  "new durga devi temple opposite": 22,
  "kinnera theater backside": 22,
  "vevekananda park": 22,
  "sfs school area": 22,
  "ganesh babu hospital road lane": 22,
  "75'-0\" road (sri sai ganesh guest house lane)": 22,
  "kranthi nagar": 24,
  "nakkavanipalem": 24,
  "shivalayam street 60 feet road": 24,
  "old resapuvanipalem": 24,
  "cmr centre back side": 24,
  "tulasipeta": 24,
  "ramatalkies road": 24,
  "vinayaka nagar": 24,
  "eenadu main road": 24,
  "p&t colony": 24,
  "tpt colony": 24,
  "amg area. ganesh nagar part": 24,
  "relliveedhi behind wipro": 24,
  "seethampeta main madhura nagar": 25,
  "chakali gedda": 25,
  "seethammpeta vinayaka temple area": 25,
  "shantipuram": 25,
  "ganesh nagar part": 25,
  "krishna temple area": 25,
  "kanakammavari veedhi": 25,
  "rajendra nagar": 25,
  "apoorva hospital road": 25,
  "mcv primary school lane": 25,
  "80 feet road": 25,
  "lalitha nagar": 26,
  "gnana nikethan school road": 26,
  "green tulasi appt.road": 26,
  "pnr complex road": 26,
  "krishna hospital road": 26,
  "chinnuru (turakapalem)": 26,
  "mosque": 26,
  "near jaggarao bridge": 26,
  "sakshi office line": 26,
  "bvk school road": 26,
  "lilitha appt. road": 26,
  "gajana appartment": 26,
  "near tonda ganapathi temple": 26,
  "lalitha pioneer club road": 26,
  "lalitha temple back side road": 26,
  "jindal ply wood beside road": 26,
  "union bank of india road": 26,
  "priyadarshini paradise back side": 26,
  "vijay kunj appt.road": 26,
  "st. marry school": 26,
  "akkayapalem": 26,
  "vagdevi school road": 26,
  "nggo's colony": 26,
  "opp sai baba temple": 26,
  "n.t. school road": 26,
  "opp venugopalaswamy temple": 26,
  "v c bank": 26,
  "icwaz bhavan": 26,
  "ramakrishna nagar near bazar": 26,
  "near sai baba temple": 26,
  "vip road": 27,
  "commissioner bunglow opposite road": 27,
  "rama talkies road": 27,
  "amar nagar": 27,
  "timpany school area": 27,
  "cbm compound area": 27,
  "sampath vinayak temple area": 27,
  "srinagar": 27,
  "e-seva back side": 27,
  "bhagatsingh colony": 27,
  "kumari veedhi": 27,
  "dondaparthi": 27,
  "mandavari veedhi": 27,
  "akkayapalem road": 27,
  "old sree surya road": 27,
  "nehru bazar road": 27,
  "kala hospital road": 27,
  "ramalayam area": 27,
  "reddy hospital road": 27,
  "circuit house": 28,
  "daspalla hills": 28,
  "harbour quarters park": 28,
  "ram nagar": 28,
  "pitandibba": 28,
  "kailasametta": 28,
  "bhanoji nagar": 28,
  "kannayyapeta": 29,
  "apsara main road": 29,
  "prakasha rao peta": 29,
  "anthony nagar": 29,
  "chandaka veedhi": 29,
  "prahladha kalyanamandapam road": 29,
  "durga hospital road": 29,
  "otagedda": 29,
  "dandu bazar": 29,
  "angadi dibba & jagadamba road": 29,
  "venkatapathiraju nagar": 29,
  "old employment office": 30,
  "kotta jalaripeta": 30,
  "kgh opp": 30,
  "kodipandelavari street": 30,
  "kummara veedhi": 30,
  "salipeta": 30,
  "kotta salipeta": 30,
  "chakali veedhi": 30,
  "super bazar area": 30,
  "paindorapeta road": 30,
  "zp road": 30,
  "surya hospital road": 30,
  "au ladies hostel road": 30,
  "ysrc p bheem nagar": 31,
  "south jail road": 31,
  "assam gardens": 31,
  "krishna gardens": 31,
  "ii town ps down": 31,
  "dabagardens": 31,
  "yellammathota": 31,
  "suryabagh": 31,
  "kanakala dibba": 31,
  "boddu naidu thota": 31,
  "apsrtc complex": 31,
  "lalitha colony": 31,
  "sbi colony": 31,
  "prakasarao peta": 31,
  "spring road & 75 feet road": 31,
  "nerella koneru road": 32,
  "allipuram road": 32,
  "karanala veedhi": 32,
  "chakrathota": 32,
  "railway quarters": 32,
  "devangula veedhi": 32,
  "krishna veedhi": 32,
  "pootivarimanyam & bheem nagar": 32,
  "krishnanagar": 32,
  "kummari veedhi": 33,
  "bangaramma metta": 33,
  "harijana veedhi": 33,
  "venkateswara metta": 33,
  "sai baba street": 33,
  "leela mahal road": 33,
  "neelamma vepa chettu road & geeth sangeeth road": 33,
  "srmt road": 34,
  "jandachettu": 34,
  "netaji nagar": 34,
  "atchiyamma peta": 34,
  "kobbarithota": 34,
  "bhupesh nagar & taraka rama colony": 34,
  "chaluvathota part": 34,
  "d.n.8-42-16": 35,
  "thamila veedhi": 35,
  "chinna stadium road": 35,
  "prasad gardens": 35,
  "periki veedhi": 35,
  "poolasandhu": 35,
  "velampeta": 35,
  "kallupakalu & 75 feet road": 35,
  "gajula veedhi": 35,
  "panda veedhi": 35,
  "agraharam veedhi": 36,
  "sunnapu veedhi": 36,
  "kotta road down": 36,
  "chengalaraopeta": 36,
  "avn college down": 36,
  "godarigothulu": 36,
  "skml strret": 36,
  "manthavari strret": 36,
  "rangireeju veedhi": 36,
  "down relli veedhi": 36,
  "upper relli veedhi": 36,
  "rajaka veedhi & town main road": 36,
  "paindorapeta": 37,
  "asipapa veedhi": 37,
  "kotta relli veedhi": 37,
  "chattalavri veedhi": 37,
  "kotta agraharamveedhi": 37,
  "agraharam veedhi & chengalaraopeta": 37,
  "gollaveedhi": 37,
  "bukka veedhi": 38,
  "kanchara veedhi": 38,
  "town hall road": 38,
  "pappula veedhi": 38,
  "gangabattula veedhi": 38,
  "jilledamudivari veedhi": 38,
  "chinnammavari veedhi": 38,
  "shivalayam street": 38,
  "thomson street": 38,
  "soldier peta": 38,
  "town main road & st.alloy's high school road": 38,
  "conveyor belt slum": 38,
  "conveyor belt": 39,
  "kota veedhi": 39,
  "potti sriramulu park": 39,
  "nallavari street": 39,
  "kurpam market": 39,
  "chagantivari street": 39,
  "vada veedhi": 39,
  "chilakapeta": 39,
  "padma nagar": 39,
  "taraka rama nagar & rama krishna nagar": 39,
  "ferry road": 39,
  "jaganadhapuram": 41,
  "babu colony": 41,
  "gnanapuram scheme houses": 41,
  "konda veedhi": 41,
  "manual street": 41,
  "post office street": 41,
  "r.c.aided school area": 41,
  "near st.peters play ground": 41,
  "railway new colony": 41,
  "railway grounds": 41,
  "seva": 41,
  "akkayyapalem 80 feet road": 43,
  "chekkuduraya building": 43,
  "hp gas godown": 43,
  "k v quarters": 43,
  "munasabu gari colony": 43,
  "nandagirinagar": 43,
  "narendra colony": 43,
  "vivekananda hospital road": 43,
  "yelamanchili vari street": 43,
  "santoshi matha temple": 44,
  "abid nagar": 44,
  "akkayapalem highway": 44,
  "andhra jyothi": 44,
  "dadi ram murthy kalyanamandapam": 44,
  "gavara thatichetlapalem": 44,
  "gowri kalyana mandapam": 44,
  "madeti gardens": 44,
  "muslim thatichetlapalem": 44,
  "shadhikhana": 44,
  "4th town police station": 46,
  "seethammadhara": 46,
  "bapuji nagar": 48,
  "indira nagar - i": 48,
  "indira nagar - ii": 48,
  "indira nagar - iv": 48,
  "indira nagar-v": 48,
  "jai bharat nagar": 48,
  "palnati colony": 48,
  "pedda kotturu": 48,
  "shivalingapuram": 48,
  "vigneswara apartment - 1": 49,
  "pr gardens": 49,
  "kamakshi nagar": 49,
  "burma camp": 49,
  "lal bahadur nagar": 49,
  "girija nagar": 49,
  "manikyamba colony": 49,
  "manchu konda thota": 49,
  "satya nagar": 49,
  "surya nagar": 49,
  "p.r.gardens": 49,
  "ajay kalam": 49,
  "murali nagar": 50,
  "singaraya metta": 50,
  "sai ram nagar": 50,
  "tenneti nagar": 50,
  "madhavadhara": 50,
  "vidya nagar": 50,
  "kalinga nagar": 50,
  "seethanna gardens": 50,
  "madhavadhara manyam": 50,
  "murali nagar estate": 50,
  "gold smith colony": 51,
  "appayya nagar": 51,
  "citti babu colony": 51,
  "mahat colony": 51,
  "bheem nagar": 51,
  "eklavya colony": 51,
  "r & b colony": 51,
  "madhavadhara vuda colony": 51,
  "air port & new police quarters": 52,
  "durga puram": 52,
  "ganesh nagar": 52,
  "gowri nagar": 52,
  "guruda colony & ambedkar nagar": 52,
  "marripalem vuda layout": 52,
  "new karasa": 52,
  "old karasa": 52,
  "old police quarters": 52,
  "netaji colony": 52,
  "bhaskar gardens": 53,
  "rana pratap nagar": 53,
  "masjaid veedhi": 53,
  "andhra kesari nagar": 53,
  "harsha nagar": 53,
  "jakhir hussain nagar": 53,
  "maharani veedhi": 53,
  "gavara veedhi": 53,
  "marripalem": 53,
  "marripalem main road": 53,
  "parvathi nagar - i": 53,
  "104 area main road": 54,
  "gajapathinagar": 54,
  "jyothi nagar": 54,
  "kancharapalem main raod": 54,
  "nalanda nagar": 54,
  "old police station area": 54,
  "ravindranagar": 54,
  "reddy kancharapalem": 54,
  "sasikala": 55,
  "d.no.49-53-10/9(17)": 55,
  "jashuvanagar": 55,
  "ashokngar": 55,
  "kothawada veedhi": 55,
  "devendranagar": 55,
  "opp mini sweage farm": 55,
  "near ramalayam temple": 55,
  "thatichetlpalem bus stop": 55,
  "kapparada": 55,
  "kancharapalem": 55,
  "jogarao nagar": 55,
  "ashok": 55,
  "dayanand nagar": 56,
  "gavara kancharapalem": 56,
  "golla kancharapalem": 56,
  "malla suri veedhi": 56,
  "nda area": 56,
  "meghadripeta defence colony": 56,
  "asivanipalem": 57,
  "bharat nagar": 57,
  "bhavani gardens": 57,
  "mes quarters": 57,
  "kv no : 1 & 2 staff quarters": 57,
  "nad civilians residential colony": 57,
  "nad colony": 57,
  "nirman park": 57,
  "ramu naidu colony": 57,
  "sakethapuram": 57,
  "subash nagar": 57,
  "syam prasad nagar": 57,
  "thummadapalem": 57,
  "malkapuram post ajantha colony": 58,
  "annamma colony": 58,
  "annapurna nagar": 58,
  "ganesh vani palem": 58,
  "kodipandela dibba": 58,
  "kunchalamma veedhi": 58,
  "kunchumamba colony": 58,
  "mulagada": 58,
  "old ramalayam": 58,
  "pilakavani palem": 58,
  "ashok nagar colony": 59,
  "checkpost": 59,
  "ex serviceman colony": 59,
  "ganapathi nagar": 59,
  "hanuman nagar": 59,
  "himachal nagar": 59,
  "himachal nagar( zinc gate)": 59,
  "kotha nakkavanipalem": 59,
  "mulagada housing colony": 59,
  "nakkavani palem": 59,
  "ganesh mandir street": 60,
  "hanuman sanjeev colony": 60,
  "indira colony": 60,
  "janatha colony part": 60,
  "jawahar": 60,
  "ramakrishnapuram": 61,
  "malkapuram": 61,
  "achi naidu thota": 62,
  "asr colony": 62,
  "cisf quarters": 62,
  "coast guard": 62,
  "durga nagar colony": 62,
  "gandhiji street": 62,
  "kranthi nagar upto dr no 71-31- 584": 62,
  "nauseena bagh": 62,
  "port quarters": 62,
  "yarada": 64,
  "gangavaram": 64,
  "pallivedhi": 64,
  "yathapalem": 64,
  "kongapalem": 64,
  "venkannapalem": 64,
  "godduvanipalem": 64,
  "new dibbapalem r.h colony": 64,
  "satyanarayanapuram": 64,
  "sanjeevagiricolony": 65,
  "bhanojithota": 65,
  "sanjeeva colony": 65,
  "vikas nagar": 65,
  "kl rao nagar": 65,
  "bhavani bapuji colony": 65,
  "new gajuwaka": 67,
  "gajuwaka main road part": 67,
  "high school road": 67,
  "pentayya nagar": 67,
  "jogavani palem": 67,
  "part": 67,
  "bojjanna konda": 67,
  "d.no. 2-25-17": 68,
  "akkireddy palem main road akkireddy palem": 68,
  "panchavati": 68,
  "mindi": 68,
  "gudivada appanna colony part": 68,
  "kalika nagar": 68,
  "giriprasad nagar": 68,
  "rajeev nagar": 68,
  "chukkavaani palem": 69,
  "nathayyapalem": 69,
  "tunglam": 69,
  "tunglam sc colony": 69,
  "bhpv township(bhel)": 69,
  "harijana jaggayyapalem": 69,
  "venkateswara colony": 69,
  "sheela nagar": 69,
  "venkatapathi raju nagar": 69,
  "chattivanipalem": 70,
  "pantulugarimeda part": 70,
  "pallavari street": 70,
  "old gajuwaka": 70,
  "chittinaidu colony": 70,
  "dasamikonda colony": 70,
  "drivers colony": 70,
  "tvn colony": 70,
  "lv nagar": 70,
  "lbs nagar": 70,
  "yerragedda colony": 70,
  "sramikanagar part": 70,
  "gajuwaka vizag -26 auto nagar": 71,
  "sundarayya colony": 71,
  "kunchamamba colony": 71,
  "dattasai nagar": 71,
  "visweswarayya colony": 71,
  "new dibbapalem": 71,
  "gurunadha rao colony": 71,
  "railway quarters vadlapudi": 71,
  "sri nagar": 71,
  "sriram nagar": 71,
  "thokada": 71,
  "chinagantyada sc colony": 72,
  "prasanthi nagar": 72,
  "chinagantyada mehar nagar": 72,
  "china nadupuru": 72,
  "old karnavani palem": 72,
  "sundarayya colony sri nagar part": 72,
  "sri nagar official colony": 72,
  "vuda colony": 72,
  "b.c. social welfare colony": 72,
  "kanithi road": 72,
  "china nadupuru part": 73,
  "gonthinavanipalem": 73,
  "kailash nagar": 73,
  "kotha karnavani palem": 73,
  "pydimamba colony": 73,
  "sanath nagar": 73,
  "seetha ram": 73,
  "dallivanipalem": 74,
  "konavanipalem": 74,
  "simhagiri colony": 74,
  "peda korada": 74,
  "pedagantyada": 75,
  "patha ayyannapalem": 75,
  "neelapuvedhi": 75,
  "musilinaidu palem": 75,
  "mollivanipalem": 75,
  "nellimukku": 75,
  "ayyannapalem": 75,
  "durgavanipalem": 75,
  "seekuvanipalem": 75,
  "seetharam nagaram": 75,
  "pedakorada": 75,
  "balacheruvu road": 75,
  "bala cheruvu sivalayam veedhi": 76,
  "korada": 76,
  "aphb colony": 76,
  "samatha nagar(2blocks)": 76,
  "st colony": 76,
  "ramachandra nagar": 76,
  "rickshaw colony": 76,
  "gopalareddy nagar": 76,
  "peda nadupuru": 76,
  "seeravani palem": 76,
  "dairy colony": 76,
  "old karnavanipalem": 76,
  "goruduvanipalem": 77,
  "palikala doddi": 77,
  "nammi doddi": 77,
  "yalamanchili doddi": 77,
  "new ginnipalem": 77,
  "old ginnivanipalem": 77,
  "maddivanipalem": 77,
  "palavalasa": 77,
  "peda devada": 77,
  "peddapalem": 77,
  "pittavanipalem": 77,
  "relangi doddi": 77,
  "matta doddi": 77,
  "butchayyapeta": 77,
  "madina bagh": 77,
  "sattar camp": 77,
  "chinapalem": 77,
  "pedapalem": 77,
  "islam peta": 77,
  "mahammed saheb peta. kanitinaidu colony": 77,
  "steel plant sector-1&ii": 77,
  "gallavani palem": 79,
  "old aganampudi": 79,
  "santhi nagar satram": 79,
  "annapaurna nagar": 79,
  "k.s.n reddy nagar": 79,
  "sanivada": 79,
  "lankelapalem karanam vari veedi": 79,
  "b.c colony": 79,
  "dasari veedi": 79,
  "s.c colony": 79,
  "konda veedi": 79,
  "sri ranga nayakula colony": 79,
  "kotturu colony": 79,
  "appikonda vari veedi": 79,
  "ganji peta": 79,
  "pujari vari veedi": 79,
  "golla peta": 79,
  "lankelapalem industries": 79,
  "sai nagar (desapatrunipalem)": 79,
  "desapatruni palem": 79,
  "jajulavani palem": 79,
  "attavani palem": 79,
  "peda madaka part": 79,
  "kondayyavalasa part": 79,
  "tadi": 80,
  "rajupalem": 80,
  "valluru and parts of gavarapalem pedda veedhi": 80,
  "santhoshimatha gudi veedhi": 80,
  "parameswari park road": 80,
  "chadaram veedhi": 80,
  "branch road": 80,
  "pallapu veedhi": 80,
  "dibba veedhi": 80,
  "budha prakasarao vreedhi": 80,
  "pvr naidu veedhi": 80,
  "budh ramadas gari veedhi": 80,
  "sathakampattu": 80,
  "china ramaswamy gudi veedhi": 80,
  "dasarigedda road": 80,
  "arundhati road": 80,
  "budha armadas street": 80,
  "demuni thota": 80,
  "karri veedhi": 80,
  "parts of gnt road": 81,
  "maszid road": 81,
  "kaspa veedhi": 81,
  "westren side of ramalayam st": 81,
  "one- way traffic road": 81,
  "metarnaty hospital road": 81,
  "reddy adi narayana veedhi": 81,
  "nidanam doddi": 81,
  "gnt road": 81,
  "botcha vari veedhi": 81,
  "sagi.subba raju gari veedhi": 81,
  "dadi bhogalingam school veedhi": 81,
  "municipal dispensary road": 81,
  "dr.appa rao road": 81,
  "kamakshamma gudi area": 81,
  "raithu sangham road": 81,
  "eastern side of 101 area": 81,
  "dadi bhoga lingam school area": 81,
  "villuri parandhamayya gari veedhi": 81,
  "kobbari thota": 81,
  "dadi vari veedhi": 81,
  "peda road": 81,
  "thotada road": 81,
  "bhogalingswamy veedhi": 81,
  "thota veedhi": 81,
  "market area": 81,
  "bandigadi veedhi": 81,
  "gandhi nagar &anjayya colony & income tax st": 82,
  "post office st": 82,
  "vijaya ramaraju peta parts of eastren side of pudimadaka road": 82,
  "new colony area": 82,
  "baru vari veedhi": 82,
  "one-way traffic road parts of parasaramuni peta": 82,
  "sarada colony": 82,
  "pudimadaka road(western side)": 82,
  "subbaram layoutcolony": 82,
  "teachers colony": 82,
  "bypass road": 82,
  "umalada road parts of narasinga rao peta": 82,
  "telephone exchange road": 82,
  "chodavaram road": 82,
  "railway track side road and chodavaram road areas. community hall areaand railway track side road area": 82,
  "sriramnagar and madhavasadhan area": 82,
  "sarada river bund area": 82,
  "mirayala colony": 83,
  "arc quarters": 83,
  "lakshmideipeta": 83,
  "pathurudu colony area wood peta": 83,
  "sarvakamadamba park st": 83,
  "velpula vedhi": 83,
  "chakala peta": 83,
  "and amanchivari veedhi": 83,
  "town girls high school area": 83,
  "kondapalli vari st": 83,
  "nagavamsam st": 83,
  "takasi veedhi": 83,
  "loka vari veedhi& malla veedhi area. goods shed road": 83,
  "railway station road": 83,
  "gandhi bomma kudali part.loka vari veedhi": 83,
  "pin code 531001 takasi veedhi part": 84,
  "mallimadugula vari veedhi": 84,
  "nagavamsam veedhi part": 84,
  "pedda veedhi part": 84,
  "malla veedhi": 84,
  "pedabhaskarayya peta": 84,
  "chinabhaskarayya peta": 84,
  "seelamanthula vari veedhi": 84,
  "thendra peta. kotni veedhi": 84,
  "railway station road pilla vari goorja part": 84,
  "neyyala veedhi part": 84,
  "peda raju peta": 84,
  "golla veedhi parts. neyyala veedhi": 84,
  "perugubazar": 84,
  "fish market area": 84,
  "vizayanagaram road": 84,
  "pilla vari gorja": 84,
  "ring road": 84,
  "kuncha vari veedhi": 84,
  "koppaka": 84,
  "knr peta": 84,
  "sirasapalli.salapuvanipalem": 84,
  "\"plot num:166-167 pharmacity colony": 85,
  "lemarthy agraharam aganampudi vizag 530046 talariavanipalem": 85,
  "dibbapalem": 85,
  "mantripalem": 85,
  "kotturu": 85,
  "sri ram colony": 85,
  "vinayaka nagar colony": 85,
  "lankelapalem": 85,
  "gonna vani palem": 85,
  "e marripalem": 85,
  "lemarthi colony": 85,
  "kotta palem": 85,
  "e-bonangi": 85,
  "payakarao peta(e-marripalem)": 85,
  "peddi naidu palem": 85,
  "aganampudi": 85,
  "dhana vari palem": 85,
  "andaman kondayyavalasa": 85,
  "chati vanipalem": 85,
  "pedamadaka part": 85,
  "karri vani palem": 85,
  "bramaramba uppara colony": 85,
  "pinamadaka": 85,
  "donkada": 85,
  "pudi vani palem": 85,
  "aganampudi kondayya valasa": 85,
  "kurmannapalem": 86,
  "vadlapudi": 86,
  "vizag-46 uppara colony": 86,
  "satavahana nagar opp nh-16": 86,
  "lella koteswara rao street": 86,
  "duvvada station road": 86,
  "bsnl office line": 86,
  "sai baba temple street": 86,
  "pavani public school opposite street": 86,
  "iti road": 86,
  "yatha palem phase-3": 86,
  "rasalamma colony": 86,
  "vuda phase-i": 86,
  "matru sree nagar": 86,
  "vuda phase-v": 86,
  "vuda phase-vii": 86,
  "talarivani palem part": 86,
  "duvvada sector-ii": 86,
  "china yathapalem": 86,
  "sairam parlor backside": 86,
  "rajulapalem kasipalem": 86,
  "simon nagar": 86,
  "fakeerthakiya": 86,
  "vadlapudi(post)": 87,
  "kurmannapalem part": 87,
  "vadlapudi r.h colony": 87,
  "vadlapudi kanithi colony main road": 87,
  "vadlapudi chakali street": 87,
  "vadlapudi muslim street": 87,
  "old vadlapudi": 87,
  "lakshmipuram colony": 87,
  "yadava street": 87,
  "kalinga street": 87,
  "telukala street": 87,
  "appikonda colony": 87,
  "tirumala nagar": 87,
  "rajulapalem part": 87,
  "siddarda nagar": 87,
  "kurmannapalem road": 87,
  "gandhibomma street": 87,
  "kanithi high school road": 87,
  "tgr nagar": 87,
  "jaggarajupeta": 88,
  "kapu jaggarajupeta": 88,
  "attavanipalem part": 88,
  "bc colony": 88,
  "karnavanipalem aganampudi": 88,
  "chandra nagar": 89,
  "adarsha nagar": 89,
  "appalanarasimha colony": 89,
  "kharavela nagar": 89,
  "kothapalem": 89,
  "nagendra nagar": 89,
  "santhosh nagar": 89,
  "pullambatla palem": 89,
  "santhoshimatha colony": 89,
  "boddeti street": 89,
  "chakalaveedhi": 89,
  "main road krishna nagar": 89,
  "madhyaveedhi": 89,
  "ramalayam veedhi": 89,
  "yellapuvanipalem": 89,
  "butchiraju palem": 90,
  "vidyuth nagar": 90,
  "seetharamarajunagar": 90,
  "susarla colony": 90,
  "butchirajupalem": 90,
  "main road": 90,
  "vinodh nagar": 90,
  "lakshmi nagar (e & f blocks)": 90,
  "lakshmi nagar (c": 91,
  "d blocks)": 91,
  "harijana colony": 91,
  "china butchirajupalem": 91,
  "old gopalapatnam": 91,
  "siva devi": 92,
  "do.no.14-7": 92,
  "r.r.v.puram": 92,
  "gopalapatnam": 92,
  "venkatapuram": 92,
  "rr venkatapuram": 92,
  "padmanabha nagar": 92,
  "nandamuri nagar": 92,
  "kamparapalem": 92,
  "bapuji indira nagar": 92,
  "community hall": 92,
  "banta colony": 92,
  "rao d.no.8-58": 93,
  "naidu thota": 93,
  "vepagunta post": 93,
  "pendurthi": 93,
  "sai durga nagar": 93,
  "balaji gardens": 93,
  "prahaladhapuram": 93,
  "simhadri nagar": 93,
  "virat nagar": 93,
  "maruthi nagar": 93,
  "lanka nagar": 93,
  "rajaji marg": 93,
  "prahaladhapuram colony": 93,
  "pallinarayanapuram": 93,
  "anjanadri colony": 93,
  "sai madhava nagar": 93,
  "sector-i": 93,
  "chandanapuri colony": 93,
  "bharath nagar": 93,
  "gollanarayanapuram": 93,
  "gangiredla colony": 94,
  "anjaneyulu nagar": 94,
  "appalanarasimham colony": 94,
  "venkata sai nagar": 94,
  "ravi nagar": 94,
  "sivalayam colony": 94,
  "gowtham nagar": 94,
  "mutyamamba colony": 94,
  "purushothapuram": 94,
  "gokuldham colony": 94,
  "bhpv teachers colony": 94,
  "sanathivanipalem": 94,
  "simhapuri colony": 94,
  "phase-ii": 94,
  "paidimamba colony": 94,
  "kalapallivari street": 94,
  "municipal office back side": 94,
  "naiduthota": 94,
  "chinnamusidiwad": 95,
  "mes layout": 95,
  "cheemalapalli": 95,
  "porlupalem": 95,
  "gavara palem": 95,
  "seshadri nagar": 95,
  "varalakshmi nagar": 95,
  "bc colony- gavara palem": 95,
  "sc bc colony - lakshmipuram": 95,
  "rama co-operative colony": 95,
  "krishnarayapuram": 95,
  "gollivillivanipalem": 95,
  "lic colony": 95,
  "papayyarajupalem": 95,
  "port colony-go vn colony": 95,
  "sc colony-ramalayam colony": 95,
  "lakshminarasimha nagar": 95,
  "lakshminarasayyamma nagar": 95,
  "nad layout": 95,
  "ratnagiri nagar": 95,
  "satabdhi nagar": 95,
  "pendurthi old village": 96,
  "telakalaveedhi": 96,
  "z.p. hs area": 96,
  "yethapeta": 96,
  "adityanagar": 96,
  "mondibanda": 96,
  "chinnamusidiwada": 97,
  "railway colony": 97,
  "savithri nagar": 97,
  "saradha nagar": 97,
  "brts road": 97,
  "sapthagiri nagar": 97,
  "hamsi nagar": 97,
  "sujatha nagar": 97,
  "a-zone": 97,
  "sujatha nagar b-zone": 97,
  "sujatha nagar c1 zone": 97,
  "c2 zone": 97,
  "anjaneya nagar": 97,
  "gopala krishna nagar": 97,
  "karmika nagar": 97,
  "subhadra gardens": 97,
  "venkatadri 3": 97,
  "5 & 6 layouts": 97,
  "dronam rajunagar": 97,
  "chinamushidiwada": 97,
  "sai baba veedhi": 97,
  "panchyat shop rooms": 97,
  "naravanipalem": 97,
  "water tank": 97,
  "gayathri": 97,
  "simhachalam": 98,
  "appannapalem": 98,
  "simhapuri layout": 98,
  "adivivaram": 98,
  "old adivivaram": 98,
  "landagaruvu": 98,
  "gantala veedhi": 98,
  "rajulavedhi": 98,
  "pushkariniveedhi": 98,
  "santhoshimatha temple": 98,
  "priya gardens": 98,
  "pydithallamma temple": 98,
  "lower gosala": 98,
  "amg hospital": 98,
  "ghot road": 98,
  "simhachalam hill": 98,
  "srinivasa kalyanamandapam": 98,
  "shipyard layout": 98,
  "priyagardens": 98,
  "balaji nagar up": 98,
  "sector-2": 98
};

// Function to find ward by area name (case-insensitive partial match)
function findWardByArea(query) {
  if (!query) return null;
  const q = query.toLowerCase().trim();
  // Exact match first
  if (AREA_TO_WARD[q] !== undefined) return AREA_TO_WARD[q];
  // Partial match
  for (const [area, ward] of Object.entries(AREA_TO_WARD)) {
    if (area.includes(q) || q.includes(area)) return ward;
  }
  return null;
}

// Function to get all areas for a ward
function getAreasForWard(wardNum) {
  return WARD_AREAS[wardNum] || [];
}