-- GVMC Smart Ward Connect - Supabase Schema setup
-- Copy and run this script in the Supabase SQL Editor (https://supabase.com)

-- 1. Create public.wards table
CREATE TABLE IF NOT EXISTS public.wards (
    ward integer PRIMARY KEY,
    name text DEFAULT ''::text,
    population integer DEFAULT 0,
    male integer DEFAULT 0,
    female integer DEFAULT 0,
    sc integer DEFAULT 0,
    st integer DEFAULT 0,
    secretariat text DEFAULT ''::text
);

-- 2. Create public.ward_areas table
CREATE TABLE IF NOT EXISTS public.ward_areas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ward_id integer REFERENCES public.wards(ward) ON DELETE CASCADE,
    name text NOT NULL,
    UNIQUE (ward_id, name)
);

-- 3. Create public.sustainability_feedback table
CREATE TABLE IF NOT EXISTS public.sustainability_feedback (
    id text PRIMARY KEY, -- format: "CSB-1719148400000"
    ward_id integer REFERENCES public.wards(ward) ON DELETE CASCADE,
    score integer NOT NULL,
    cleanliness integer NOT NULL,
    water integer NOT NULL,
    transport integer NOT NULL,
    green integer NOT NULL,
    roads integer NOT NULL,
    pollution integer NOT NULL,
    disaster integer NOT NULL,
    governance integer NOT NULL,
    date text NOT NULL, -- format: "23 Jun 2026"
    created_at timestamp with time zone DEFAULT now()
);

-- 4. Create public.complaints table
CREATE TABLE IF NOT EXISTS public.complaints (
    id text PRIMARY KEY, -- format: "GVMC-1719148400000-1234"
    ward_id integer REFERENCES public.wards(ward) ON DELETE CASCADE,
    colony text DEFAULT ''::text,
    category text NOT NULL,
    description text NOT NULL,
    photo text, -- base64 representation of the image
    status text DEFAULT 'Pending'::text, -- Pending, In Progress, Resolved
    priority text DEFAULT 'Medium'::text, -- Low, Medium, High
    date text NOT NULL, -- format: "23 Jun 2026"
    created_at timestamp with time zone DEFAULT now()
);

-- 5. Create public.profiles table (matches auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    username text,
    role text DEFAULT 'Ward Officer'::text, -- Admin, Ward Officer, Data Entry Operator
    updated_at timestamp with time zone DEFAULT now()
);

-- 6. Disable Row Level Security (RLS) for simple integration, or customize as needed
-- Note: In a production app, you should enable RLS and use permissive Policies.
ALTER TABLE public.wards DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ward_areas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sustainability_feedback DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;

-- 7. Trigger to automatically create a profile in public.profiles when a new auth user is created
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    COALESCE(new.raw_user_meta_data->>'role', 'Ward Officer')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Recreate trigger if exists
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
