# Generated by Django 6.0.6 on 2026-06-23 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('population', models.IntegerField(default=0)),
                ('male', models.IntegerField(default=0)),
                ('female', models.IntegerField(default=0)),
                ('sc', models.IntegerField(default=0)),
                ('st', models.IntegerField(default=0)),
                ('secretariat', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Ward Officer', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityFeedback',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('cleanliness', models.IntegerField()),
                ('water', models.IntegerField()),
                ('transport', models.IntegerField()),
                ('green', models.IntegerField()),
                ('roads', models.IntegerField()),
                ('pollution', models.IntegerField()),
                ('disaster', models.IntegerField()),
                ('governance', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustainability_feedback', to='wards.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('colony', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('photo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('priority', models.CharField(default='Medium', max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='wards.ward')),
            ],
        ),
        migrations.CreateModel(
            name='WardArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='wards.ward')),
            ],
            options={
                'unique_together': {('ward', 'name')},
            },
        ),
    ]
